### ISSUE TITLE
SZWEAUTH is cloned, causing later updates to not be used

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#1031]
**Describe the bug**
zowe-install-xmem.sh clones the SZWEAUTH library to $loadlib, and adjusts the customized PROCLIB members to use $loadlib instead of SZWEAUTH. 
This copy only happens during the initial customization, which means that any updates to SZWEAUTH done later by applying service are not seen by the STC.

**To Reproduce**
review logic in scripts/utils/zowe-install-xmem.sh 

**Expected behavior**

Cloning and customizing parmlib members is required, but for loadlibs, the installed version msut be used.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by John-A-Davies** [comment]
**JohnDavies(opens in new tab)  11:27 AM**
Hi Onno.  Is there an intention to change how we deal with hlq.SZWEAUTH and hlq.SZWESAMP, namely to no longer copy them to customer datasets, like we do below?
```

<zowe-install-xmem.sh>
Copying load module ZWESAUX
Info:  module ZWESAUX has been successfully copied to dataset ZOE.ZIS.SZISLOAD
Copying load module ZWESIS01
Info:  module ZWESIS01 has been successfully copied to dataset ZOE.ZIS.SZISLOAD
Copying SAMPLIB member ZWESIP00
Info:  member ZWESIP00 has been successfully copied to dataset ZOE.ZIS.SISSAMP

```
... but instead to make hlq.SZWEAUTH and hlq.SZWESAMP the 'real' datasets that the customer system uses?
**JohnDavies(opens in new tab)  11:32 AM**
If so, I'd be against it.  Mainly because they are SMP/E targets, and if they contain other customer members, then there is a conflict of control.  It might be OK if hlq.SZWEAUTH and hlq.SZWESAMP were used exclusively by Zowe.
**Onno Van den Troost(opens in new tab)  2:11 PM**
SZWEAUTH is a 'real' dataset that must be referenced by the ZWESISTC started task to ensure the server is running with the latest code we ship. The customer is not supposed to change anything here.
SZWESAMP holds the 'master' samples. If changes are required, then a copy must be made to another dataset and that copy must be customized. As with SZWEAUTH, the customer is not supposed to change anything here as everything is overwritten on the next install.
Zowe extenders should be creating their own datasets to avoid ownership issues.
2:14
That is why I initially proposed to create a job that copies the samples needed for setup to new libraries, and semi-customize in the copy process (since we already know some info, like the location of SZWEAUTH)
**JohnDavies(opens in new tab)  2:34 PM**
I agree that SZWEAUTH and SZWESAMP are real datasets that only SMP/E should change.  I've never used them in situ, but always copied them to ZOE.ZIS.SZISLOAD and ZOE.ZIS.SISSAMP as named in the ZWESASTC PROC.  The DSNs in that PROC could instead be changed to refer to SZWEAUTH and SZWESAMP which might be better.  The SZWESAMP(ZWESASTC) has to be copied to the JES PROCLIB concatenation, so maybe that one is a special case.  So, apart from ZWESASTC, what do you recommend; copy SZWEAUTH and SZWESAMP to SZISLOAD & SISSAMP, or not?
**Onno Van den Troost(opens in new tab)  2:40 PM**
SZWEAUTH should never be copied, as that introduces the risk of the started task working with an older copy. The PROC should always reference SZWEAUTH.
**JohnDavies(opens in new tab)  2:41 PM**
OK, that's fine by me.
**Onno Van den Troost(opens in new tab)  2:45 PM**
As for ZSWESAMP, things that need customization definitely have to be copied out before customization. The picture is not as black-and-white when it comes to referencing SZWESAMP from within a PROC or other member. If you are referencing something is is likely to be customized (and thus first copied out), it makes sense to point to the default copy-out location to limit the number of changes that need to be done. If chances are slim that a referenced member is customized, then it makes sense to reference it in SZWESAMP for the same reason of limiting the number of required changes.
**JohnDavies(opens in new tab)  2:51 PM**
I'm happy for the ZWESASTC PROC in the JES PROCLIB to refer to SZWESAMP(ZWESIP00) because I've never had a reason to change that.  And yes, it should refer to SZWEAUTH in its STEPLIB.
**Onno Van den Troost(opens in new tab)  2:53 PM**
works for me
**JohnDavies(opens in new tab)  2:59 PM**
Good.  That means a bit of a re-write for https://docs.zowe.org/stable/user-guide/configure-xmem-server.html#copy-cross-memory-data-set-members-manually and surrounding topics.
docs.zowe.org
Installing and configuring the Zowe cross memory server (ZWESISTC) | Zowe Docs(opens in new tab)
Version 1.11.x LTS
3:00
... not by you.

**Comment by stevenhorsman** [comment]
@OnnoVdT - has this item been completed (eventually) with PR #1551 ?

**Comment by OnnoVdT** [comment]
I think it is. I provided the doc update to UA and did the code update in zowe-install-xmem.sh, which did cause some problems because I did not adjust the test-pipeline. But my understanding is that you/Jack fixed that part and all is working now. Hold info about this was added via #1395.
