### ISSUE TITLE
Automate the build process for Zowe z/OS compoments as z/OSMF Portable Software Instance

### ISSUE THREAD

**Issue by jp669844** [zowe/zowe-install-packaging#1174]
@muzikovam Please describe the process here.

**Comment by muzikovam** [comment]
**REXX** script that is creating Portable Software Instance using **z/OS client web enablement toolkit** and **z/OSMF REST APIs**:
1. Add Software Instance with SMP/E CSI, target zone name and system nickname, where the SMP/E was installed(`CIZT_SMPE_HLQ_CSI, CIZT_SMPE_TARGET_ZONE, CIZT_ZOSMF_SYSTEM`). For calling z/OSMF REST API there is needed __host__, port(`CIZT_ZOSMF_PORT`), __userid, password__ and SAF KeyRing (using the default `CIZT_ZOSMF_SAFKEYRING`).
2. Load the information about installed products, features, and FMIDs into the z/﻿OSMF Software Management task database.
3. Check if loading finished otherwise the Portable Software Instance wouldn't be complete. 
4. Generate JCL with `//ZWEPSI02 JOB` job statement to a temporary dataset that is allocated at the beginning of the scripts (using 'CIZT_PSI_DSN` and `CIZT_PSI_VOLSER`) and that will create a Portable Software Instance in CIZT_TMP/export.
5. Check if the generation of JCL is finished and submit the JCL.

_Obstacles: host, userid and password exist only in Jenkins, not available on the server._

**Comment by muzikovam** [comment]
Change of plans: There will be bash script running directly on Jenkins so it will have access to host, userid and password. There will be used curl for REST API calls.

**Comment by muzikovam** [comment]
Waiting for ZLC decision.

**Comment by jp669844** [comment]
https://github.com/zowe/zlc/issues/171

**Comment by MarkAckert** [comment]
Steps:
- z/OSMF on Marist Environment [Check z/OSMF configuration requirements]
- Access to Marist Environment (Modify Access)
- Build PSI Manually w/ z/OSMFUI
- Build Automation   [ REST / Selenium ]
- Build Pipeline using Jenkins
- Integrate into release process
- Test Automation    [ REST / Selenium ]
- Documentation (User-Facing)
- Documentation (Internal)

NOT Covered Here:
- Configuration Workflow

**Comment by MarkAckert** [comment]
PSWI has been delivered with Zowe 2.x
