### ISSUE TITLE
Package format of plugins

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#1249]
@jackjia-ibm commented on [Wed Mar 18 2020](https://github.com/zowe/zlc/issues/172)

Currently Zowe plugins don't have a consistent package format, we will need some guidance for the contributors what the package should look like. The format may also be related of the package management system we will choose.

The existing package management system Maven and NPM are not ideal for generic format. Zowe plugins may be in both Java or Node.js language, or in the future Python. We need a consistent format support all of them.

Ideally this format should:

- be language neutral,
- have a meta file defines what the plugin itself,
- define the purpose of plugin,
- define pre-reqs of the plugin (zowe components, extra systems, other plugins, etc),
- define the install, upgrade, uninstall, launch (dynamic or require Zowe to be restarted, etc), verify suggestions or scripts.

Conda could be potential package management system we can use.

---

@1000TurquoisePogs commented on [Wed Mar 18 2020](https://github.com/zowe/zlc/issues/172#issuecomment-600611342)

Currently the only codebase that doesn't have a problem with packing is the CLI because thus far it's embraced nodejs and so npm is the logical solution.
However, has/will Zeepy's inclusion changed that? Will we see users of a python client sdk looking to a python-based repo for python-based plugins? Sorry if I'm misunderstanding the purpose, maybe they don't overlap at this level. But if they did, then I think the question applies there too.

---

@armstro commented on [Wed Mar 18 2020](https://github.com/zowe/zlc/issues/172#issuecomment-600916848)

Review of this item at ZLC today - thought was to leave as ZLC issue until we determine a "better home" for it. Indicates need for an "official Architect squad" to have a backlog of issues to work.

**Comment by jackjia-ibm** [comment]
Thanks @1000TurquoisePogs and others for the input, here is a brief summary of discussion on Architecture call at Apr 21, 2020 (please feel free to edit/add if I missed any points):

- conda can fit several requirements above, like it's language neutral, has already defined meta.yaml file format which can define the general purpose of the package and install hooks. It also has mechanism to define dependencies.
- If we use conda as package management software, we need to pre-req anaconda on z/OS, or we can ship anaconda along as zowe package.
- conda has ability to define private channel, which solves the concerns from customer of downloading packages from unverified public website.
- With Zeepy, we may also need to consider supporting Python plugins. How this package manager software works with pip.
- It will be good if the package definition can define pre/post install actions. More actions we may want to have like, verifying installation, registering the component to Zowe instance, etc. Both conda/npm have the ability to define this.
- npm is another choice but more align to node.js packages. Will need to investigate if it's a good fit for java plugins, or even python package.
- If we use npm, should we publish under npmjs.org @zowe scope. Or maybe Github Packages is another option.
- If we need to separate different kind of plugins into different package repositories instead of having one unified place. For example, separate api, desktop, cli/client plugins into 3 repositories.
- We can setup a work group on this topic after SSO changes are settled.

**Comment by jackjia-ibm** [comment]
Package format with manifest implementation was merged with https://github.com/zowe/zowe-install-packaging/issues/1769. Related documentation had also been updated.
