### ISSUE TITLE
Revisit Zowe smoke test to reflect changes have been added to Zowe

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#1292]
*Customer content*

**Is your feature request related to a problem? Please describe.**

With evolving of Zowe, many API endpoints have been updated, and the smoke test cases should be revisit to reflect the changes.

**Describe the solution you'd like**

The test cases may be reasonable:

- Test jobs/data-sets API v2 endpoints.
- Use data-sets files API to test USS file reading, re-enable `tests/sanity/test/explorer/test-api-uss.js` to use proper API.
- Test SSO function provided by APIML.
- Revisit skipped test cases and remove if they are not valid any more.

**Comment by jordanCain** [comment]
Once the Desktop offers SSO, There's a chance it will make it in 1.11.0 but otherwise it will be 1.12.0 we can test the SSO functionality by removing the authentication steps in the e2e explorer-mvs/jes/uss tests.

Testing of the v2 endpoints should in theory be as simple as duplicating the test with a different auth header (This is how we achieved it in the integration tests of the individual components requiring almost no code duplication)

**Comment by jackjia-ibm** [comment]
Thanks Jakub, I think some scenarios are covered by https://github.com/zowe/zowe-install-packaging/pull/1345.

**Comment by balhar-jakub** [comment]
I believe that we have definitely test case for
- Test jobs/data-sets API v2 endpoints.
As for test SSO function we provide tests which verify authentication via following ZOSM/v methods
- Cookie with the JWT token
- Cookie with Ltpa token
- Basic Authentication in Authorization header
- Bearer with JWT token in Authorization header

**Comment by jackjia-ibm** [comment]
We may need to constantly revisit test coverage, but for the particular items listed at the original post have all be resolved. Close for now.
