### ISSUE TITLE
More configuration steps to include in JCL for MVS system users

### ISSUE THREAD

**Issue by xwu0226** [zowe/zowe-install-packaging#1356]
*Customer content*

For some of the modification work that needs to be done withing USS for ZOWE there are sample JCL jobs in the SAMPLIB, but not all. It would be helpful to the MVS oriented user if all USS manipulation requirements were se up with a series of JCL jobs in SAMPLIB and these jobs thourighly tested and documented.

**Comment by F-LEMANER** [comment]
I agree this.
In a shop with 70 z/OS partitions, we don't work by manually executing scripts, this is impossible.
We use deployment method with JCLs using symbols and we keep the jobs output results in datasets so that all team members be able to act in case of problem consecutive to new version installation.

**Comment by Martin-Zeithaml** [comment]
Will be solved by #3718.
