### ISSUE TITLE
Pipeline fails when partitioned datasets are full

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#1379]
**Describe the bug**
The pipeline fails (ABEND D37 or E37).  This is because a PDS is full.

**To Reproduce**
1. Run the builds for a few days(?)
2. See ABEND

**Expected behavior**
No ABENDs D37 or E37 (or B37).

Normal practice is to regularly compress partitioned datasets that are frequently updated.  Therefore I would suggest that a COMPRESS step should be added (somewhere in Jenkins/Ansible), often enough to prevent each PDS becoming full.

**Additional context**
@stevenhorsman (enter link to failed build here)

**Comment by jackjia-ibm** [comment]
@John-A-Davies we may not be able to add this to install test pipeline. Probably a cron job running on the server is a better place to compress few data sets we are using. The reasons are:

- we do define to use the proclib which failed recently because based on the doc, `zowe-install-xmem.sh` doesn't declare to support to use `auto`. But the proclib used for `zowe-install-proc.sh` is using `auto`. So the ansible script doesn't really know which proclib the script will use except for adding same checking logic.
- it still depends on type of the data set. some of them they should be compressed, some we are using may not.

So i think this is mainly a sys admin task, rather than adding to our pipeline.

**Comment by John-A-Davies** [comment]
Agreed; a `cron` job on the z/OS server is fine.  Only PDS need this, PDSEs don't.  Adjust the frequency of the compress job as required, depending on how many updates are made to the members of the PDS.

**Comment by jackjia-ibm** [comment]
Other actions need to add:

- clean up /ZOWE/tmp & /tmp folder for known folder/file patterns

**Comment by jackjia-ibm** [comment]
Related pipeline is setup here https://wash.zowe.org:8443/view/CI-CD/job/daily-cleanup/job/master/ and is defined here https://github.com/zowe/zowe-dependency-scan-pipeline/blob/master/Jenkinsfile.cleanup

**Comment by jackjia-ibm** [comment]
We had converted ZOWEAD3.PARMLIB and ZOWEAD3.PROCLIB to library so they don't have this issue anymore.

If we have other datasets require regularly cleanup, we need to add to the cleanup pipeline. @John-A-Davies are you ok to close this item?

**Comment by John-A-Davies** [comment]
Please remind me of the location of the code that converted ZOWEAD3.PARMLIB and ZOWEAD3.PROCLIB to library (i.e. PDSE).

**Comment by jackjia-ibm** [comment]
The PDS format parmlib/proclib were deleted and recreated with this automation: https://github.com/zowe/zowe-install-packaging/blob/staging/playbooks/roles/configure/tasks/install_xmem_server.yml

**Comment by John-A-Davies** [comment]
I'd recommend doing the same for
```
raw: tsocmd "allocate da('{{ zowe_xmem_parmlib }}') dsntype(pds)
```
if LIBRARY is allowed for that dataset, and I'd hope it is.

**Comment by jackjia-ibm** [comment]
We have switched to use Library instead of PDS, so COMPRESS is not needed.
