### ISSUE TITLE
Zowe-install-iframe-plugin.sh hardcodes the app version to 1.0.0

### ISSUE THREAD

**Issue by jordanCain** [zowe/zowe-install-packaging#1425]
Currently any iframe plugin that's installed to the Zowe app framework is version 1.0.0 so there's no way for a user to report the version they're using.

**Describe the solution you'd like**
The zowe-install-iframe-plugin.sh should take a parameter that specifies the version that is being installed.
A follow up item would be required for all iframe apps to pass this version parameter in their configure scripts. if no parameter is provided then defaulting to version 1.0.0 would be acceptable.

---
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** Desktop user
**I want** to be able to see the iframe app version i am using
**so that** I can report bugs accurately

#### Acceptance Criteria

**Scenario 1:*
*Given* An iframe app being used in the desktop/app framework
*When* an error occurs
*Then* I can look at the properties of the app and see the correct version number

**Comment by stevenhorsman** [comment]
Given that the parameter list is already pretty lengthy (5), I'm a bit concerned about adding an optional parameter as is because it means we can't extend it in future as the ordering is required. (We currently have an optional 6th parm, but I think it can be removed as it was for backwards compatibility)
I'd like to propose that we switch to a getopts model, but (assuming I can work it out), leave the 5 current parameters working if not specified in the opts.
eg `zowe-install-iframe-plugin.sh "org.zowe.plugin.example" "Example plugin" "https://zowe.org:443/about-us/" "/zowe/component/plugin" "/zowe_plugin/artifacts/tile_image.png"` works as currently in backwards compatibility mode

new getopts mode: `zowe-install-iframe-plugin.sh -i "org.zowe.plugin.example" -s "Example plugin" -u "https://zowe.org:443/about-us/" -d "/zowe/component/plugin" -t "/zowe_plugin/artifacts/tile_image.png" [-v "1.0.0"]`

@jordanCain - does this make sense/work for you? I can research if we can get long names of options to work on z/OS as well to try and make it clearer eg. `--tileimage` vs `-t`.
