### ISSUE TITLE
High Availability: Research z/OSMF HA

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#1474]
Zowe cannot be considered as highly available unless its downstream dependency, z/OSMF, is also highly available. 

* How Zowe works with HA enabled z/OSMF (code/hot backup or z/OSMF on SYSPLEX)
  - Learning from z/OSMF
* Can we document in our HA that z/OSMF HA should also be enabled

**Comment by jackjia-ibm** [comment]
# z/OSMF HA Q/A

## From Joey, Jul 21

1. We would also like to learn more about running z/OSMF on a single z/OS system.

Typically we suggest user to setup two z/OSMF with DVIPA in different z/OS systems to avoid single point failure. If we are talking about one single z/OS system, then overall high availability would be fragile as problem could be happened in several layers such as Java, Liberty, USS, etc in the single system. But I think user can still setup DVIPA for two z/OSMF servers in the single z/OS system so that z/OSMF itself could have Warm Standby level of high availability, although DVIPA for two zOSMF in one z/OS system has not been tested before. 


2. The z/OSMF endpoint differences and how it affects HA

I list the z/OSMF REST APIs Zowe is using below based on my understand. The stateful difference and impacts to HA are also listed:

- REST Jobs API:
  Stateless. Should be able to support Active-Acitve mode. We know some customers are using it in Hot-Standby mode in production system.
- REST Data set and file API
  Stateless. Should be able to support Active-Active mode. We know some customers are using it in Hot-Standby mode in production system.
- REST Console API
  Stateful because we would like to reuse undercover TSO address space and EMCS console for same user. So Warm-Standby is the supported mode for REST Console API. However, if the user case is just issue command and get command response, Hot-Standby mode should also work in most cases for REST Console API. 
- REST TSO API
  Stateful because we would like to reuse undercover TSO resource. The operations of REST TSO API all depend on the TSO address space ID maintained in z/OSMF server. And those TSO address space ID are cleaned up if the z/OSMF server is down. So this means you can setup Hot-Standby for REST TSO API, but if the switch between active and standby zOSMF server really happens, user won't be able to get the information of previous created TSO address space and needs to recreate TSO address space for later requests.  
- REST Notification API
  As long as the Notification settings are kept the same in both z/OSMF servers, REST Notification API should be stateless. So Hot-Standby or even Active-Active should work for this API. 

## Related links:

- [Configuring z/OSMF for high availability](https://www.ibm.com/support/knowledgecenter/SSLTBW_2.3.0/com.ibm.zos.v2r3.izua300/izuconfig_HighAvailabilityConfiguration.htm)
- [Enabling single sign-on between z/OSMF instances](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.izua300/IZUHPINFO_SSOSetup.htm)

## More Questions

- Differences between Active-Active and Hot-Standby.
- For the Warm-Standby mode, I found the link shows on slide 4 doesn't work for me. Do you have the original external link? I found some information on Knowledge Center related to configure primary/secondary z/OSMF, but not sure if that's the right article about warm standby.
- Related to authentication statefulness and HA:
  * Is SSO required for z/OSMF HA Hot-Standby mode.
  * I saw a line on z/OSMF SSO documentation: The user ID of the user must exist and be the same in all System Authorization Facility (SAF) user registries. If we have 2 z/OSMF instances running on 2 z/OS systems, and they both have same user ID JACK, but password are different, is this an acceptable case? I never decrypt the LTPA2 token, but assume it include user id. In this case, if the user is authenticated on one z/OSMF and received a token, is the token valid on the other z/OSMF instance?
  * If we switch over to a warm standby z/OSMF, usually what's the interruption we can expect? For interruption duration, can we say it's the time for starting a standby service? After switched, do we require re-authenticate? Or this may depend on how we setup the two instances.
- Related to "Persist data"
  * do we store anything related to authentication
  * what's the format of persist data (file, data set, or other structured file like db)
  * is there special configuration to protect the persist data from un-authorized access
- What is expected when we access Stateful APIs in HA environment.

**Comment by jackjia-ibm** [comment]
More Q/A with Joey:

- I would like to understand more about the differences between Active-Active and Hot-Standby. **<Joey> Active-Active means primary and backup z/OSMF can be active (typically, in the same sysplex) and functioning at the same time which typically means can be used for workload balancing. Hot-Standby means although the backup z/OSMF is active, it will only take workload when primary z/OSMF is down. </Joey>** 
- For the Warm-Standby mode, I found the link shows on slide 4 doesn't work for me. Do you have the original external link? I found some information on Knowledge Center related to configure primary/secondary z/OSMF, but not sure if that's the right article about warm standby. **<Joey> Here it is: https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.2.0/com.ibm.zos.v2r2.izua300/IZUHPINFO_CreatingBackupInstance.htm </Joey>**
- Related to authentication statefulness and HA:
  * Is SSO required for z/OSMF HA Hot-Standby mode. **<Joey> No, typically these 2 z/OSMF should share same SAF DB so that same user credential can work for both z/OSMF. </Joey>**
  * I saw a line on z/OSMF SSO documentation: The user ID of the user must exist and be the same in all System Authorization Facility (SAF) user registries. If we have 2 z/OSMF instances running on 2 z/OS systems, and they both have same user ID JACK, but password are different, is this an acceptable case? I never decrypt the LTPA2 token, but assume it include user id. In this case, if the user is authenticated on one z/OSMF and received a token, is the token valid on the other z/OSMF instance? **<Joey> As I mentioned above, SSO is not required for z/OSMF HA configuration as two z/OSMF in the HA setup typically share same SAF DB. The SSO topic typically is mentioned when you have multiple sysplex and z/OSMF in each sysplex needs to communicate with each other so that one z/OSMF could provide cross-sysplex view. As for your question, I think it will be valid but I am not sure. Let me check with Liberty SME. </Joey>** 
- If we switch over to a warm standby z/OSMF, usually what's the interruption we can expect? For interruption duration, can we say it's the time for starting a standby service? After switched, do we require re-authenticate? Or this may depend on how we setup the two instances. **<Joey> Usually it's the startup time of the standby z/OSMF which depends on system configuration. In our SVT system which is a real hardware, it takes about 30 seconds to start z/OSMF. Worst case, in a simulated environment like zPDT, it could take more than 20 minutes to startup z/OSMF. But I am not too concerned about zPDT because HA for a zPDT isn't perfect anyway. On the other hand, we are improving the startup time of z/OSMF. So this could be reduced significantly in short term. Regarding to re-authentication, in Warm-Standby mode, primary z/OSMF shares same configuration and SAF DB with backup z/OSMF. So the ltpatoken generated by primary z/OSMF is also honored by backup z/OSMF. There is no need to re-authenticate. </Joey>**
- Related to "Persist data"
  * do we store anything related to authentication user sessions? **<Joey> I am not sure what things you are referring to. There are some key information used by Liberty for authentication is saved in z/OSMF persist data file system. </Joey>**
  * what's the format of persist data (file, data set, or other structured file like db)? **<Joey> The format of persist data varies. But they are all USS files typically mounted to /global/zosmf/. </Joey>**
  * is there special configuration to protect the persist data from un-authorized access? **<Joey> There are two sorts of data in z/OSMF data file system. One is z/OSMF configuration data, only accessible by z/OSMF admin user group. The other one is z/OSMF application data, only accessible by z/OSMF server user id which is IZUSVR by default. This server user id is a special user id and can not be logon by any user. </Joey>**
- What is expected when we access Stateful APIs in HA environment. **<Joey> If you access Stateful API in an Active-Active or Hot-Standby configuration, request may fail because request may depend on earlier state which is only visible in one of the two z/OSMF servers. If you access Stateful API in a Warm-Standby configuration which is supported by z/OSMF in general, since primary z/OSMF and backup z/OSMF are sharing same data file system, the state is generally shared. </Joey>**

**Comment by jackjia-ibm** [comment]
This work will also be moved to 2020PI4 to validate the configurations.

**Comment by MarkAckert** [comment]
Continued research based on prior suggestions

Outcome:
* Configuration documentation or guidance for users installing Zowe in Sysplex

**Comment by NayerNajafi** [comment]
The z/OSMF configuration we would require for Zowe HA in Sysplex is as follows:
**Multiple z/OSMF servers and autostart groups per sysplex**
![image](https://user-images.githubusercontent.com/44011615/99289057-75702580-280a-11eb-862e-f3e411833d03.png)
more than one z/OSMF server (independent z/OSMF) is to be autostarted in a sysplex. Suppose, for example,
that you have a sysplex of two systems: A, B. You plan to have System A autostart a server and similarly, System B will autostart a server.
1- Each system uses a different IZUPRMxx member with different settings for AUTOSTART_GROUP.
- instance1 AUTOSTART_GROUP(IZUDFL1)
- instance2 AUTOSTART_GROUP(IZUDFL2)
- each instance uses a shared file system with a unique mount point for each AUTOSTART group that be automatically started :
  /global/zosmf/zosmf1
  /global/zosmf/zosmf2

2- System A autostarts a z/OSMF server.
3- System B autostarts a z/OSMF server.
4- they are connected to the same z/OSMF Angel
5- they are using the same port (default 443)

**Comment by jackjia-ibm** [comment]
Sorry @NayerNajafi , after today's call, David raised a question I missed before about configuring DVIPA for z/OSMF. So I re-opened this issue and see if we can find out more details. Thank you!

**Comment by NayerNajafi** [comment]
**Configuring z/OSMF for high availability**
Zowe requires z/OSMF Active-Active HA mode. Active-Active means primary and backup z/OSMF can be active (typically, in the same Sysplex) and functioning at the same time which typically means can be used for workload balancing.
The following TCP/IP Sysplex networking DVIPA configuration ensures the availability of z/OSMF. Suppose, for example,
that you have a Sysplex of two systems: A, B:

1- Enable dynamic XCF on each host:
`IPCONFIG DYNAMICXCF x.x.x.A 255.255.255.0 1` for SYSA
`IPCONFIG DYNAMICXCF x.x.x.B 255.255.255.0 1` for SYSB

2- Define a dynamic VIPA (DVIPA) for both systems:
```
VIPADYNAMIC                                                      
  VIPADEFINE  255.255.255.0 x.x.x.V
  VIPADISTRIBUTE DEFINE SYSPLEXPORTS x.x.x.V PORT 443 DESTIP
          x.x.x.A 
          x.x.x.B                                                              
ENDVIPADYNAMIC
```
**Note:**
- x.x.x.A is SYSA's IP Address
- x.x.x.B is SYSB's IP Address
- x.x.x.V is DVIPA

![image](https://user-images.githubusercontent.com/44011615/99843833-25fa6400-2b40-11eb-884f-ce5ac2fa05a1.png)
The Sysplex Distributor routes application requests to a high availability (HA) server on a particular system.

**Comment by NayerNajafi** [comment]
Here is the slides for today's z/OSMF presentation:

[zOSMF in Sysplex.pptx](https://github.com/zowe/zowe-install-packaging/files/5674510/zOSMF.in.Sysplex.pptx)

FYI: @jandadav @jackjia-ibm

**Comment by NayerNajafi** [comment]
Related issue [#858](https://github.com/zowe/api-layer/issues/858)

**Comment by jackjia-ibm** [comment]
For the purpose of preparing the draft, this github issue had been fulfilled. We have implementation issues to track progress.

**Comment by jackjia-ibm** [comment]
Related verify/document task: https://github.com/zowe/zowe-install-packaging/issues/1863
