### ISSUE TITLE
HA Research: CLI Interaction with HA services 

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#1475]
Does the CLI need to be configured different for HA services? 

* SYSPLEX-enabled z/OSMF?
* HA APIML?

**Comment by MarkAckert** [comment]
@dkelosky do you know if the CLI "just works" in a HA situation for backend services? 

My expectation is nothing should change, but want to confirm...I know z/OSMF had some odd behaviors submitting jobs to various LPARs in a PLEX.

**Comment by MarkAckert** [comment]
Run CLI tests against Sysplex environment, document results and open new issues if necessary

**Comment by NayerNajafi** [comment]
I did some initial CLI tests with z/OSMF HA (Active-Active) mode in Sysplex environment.

**Question: Do profiles or other CLI configuration parameters change in a SYSPLEX environment?**
If z/OSMF HOSTNAME in IZUPRMxx is configured with DVIPA address, we should create CLI zosmf-profile with DVIPA:
`zowe profiles create zosmf-profile zhaplex --host x.x.x.x --port 443 --user user1 --password pass1 --reject-unauthorized false`
This approach allows users to connect to a z/OSMF server active in Sysplex using the same IP address, regardless of which system is running z/OSMF.

For instance, if we issue CLI command **zowe zosmf check status --zosmf-profile zhaplex** to check z/OSMF availability, once it connects to z/OSMF running on system1 and at the second attempt, it connects to running z/OSMF on system2.

![image](https://user-images.githubusercontent.com/44011615/100258195-c40d7600-2f14-11eb-876f-5bc795131268.png)

**Comment by NayerNajafi** [comment]
**Pre-req:** z/OSMF Sysplex / HA Environment setup can be found in issue #1474

**Comment by NayerNajafi** [comment]
**Pre-req:** How to configure zOSMF HA for Zowe in Sysplex:
https://github.com/zowe/zowe-install-packaging/wiki/Configure-zOSMF-HA-for-Zowe-in-Sysplex

**Comment by NayerNajafi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Zowe CLI Interaction with z/OSMF HA services](https://trello.com/c/SKekccd8/11-zowe-cli-interaction-with-z-osmf-ha-services)

**Comment by NayerNajafi** [comment]
**Task 1: Run CLI tests against Sysplex environment, document results and open new issues if necessary**
For example, suppose a Sysplex consists of two z/OS systems (SYSA, SYSB). z/OSMF server A (IZUSVRA) is autostarted on SYSA and similarly, z/OSMF server B (IZUSVRB) is autostarted on SYSB. IZUSVRA as preferred receives all incoming requests.
- REST Data set and file Services (Stateless):
  When failover occurs, Dynamic VIPA takeover will happen, z/OSMF server B (IZUSVTB) becomes the preferred server and accepts all new incoming requests.
- REST Jobs API (Stateless):
  When failover occurs, Dynamic VIPA takeover will happen, z/OSMF server B (IZUSVTB) becomes the preferred server and accepts all new incoming requests.
- REST TSO API (Stateful):
  Stateful because we would like to reuse undercover TSO resource. The operations of REST TSO API all depend on the TSO address space ID maintained in z/OSMF server. And those TSO address space ID are cleaned up if the z/OSMF server is down. So this means you can setup Hot-Standby for REST TSO API, but if the switch between active and standby z/OSMF server really happens, user won't be able to get the information of previous created TSO address space and needs to recreate TSO address space for later requests.
- REST Console API (Stateful):
  Stateful because we would like to reuse undercover TSO address space and EMCS console for same user. So Warm-Standby is the supported mode for REST Console API. However, if the user case is just issue command and get command response, Hot-Standby mode should also work in most cases for REST Console API.

**Comment by NayerNajafi** [comment]
SSO is not required for z/OSMF HA configuration as two z/OSMF in the HA setup typically share same SAF DB. 
The SSO topic typically is mentioned when you have multiple Sysplex and z/OSMF in each Sysplex needs to communicate with each other so that one z/OSMF could provide Cross-Sysplex view.
