### ISSUE TITLE
HA: Draft plan to reach high availability (containers) 

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#1478]
Taking prior component HA research, create a plan for Zowe to become highly available in container environments.

TBD: Orchestrators like K8S

Proof of concept the plan

**Comment by jackjia-ibm** [comment]
As containerization is more of a concern related to HA, here is a deck to kick of the discussion: 
[Zowe-Containerization.pptx](https://github.com/zowe/zowe-install-packaging/files/5292865/Zowe-Containerization.pptx). The first discussion was held at Sep 24th.

We will do more discussion and research in PI4.

**Comment by jackjia-ibm** [comment]
Here are few research items right now in my mind:

1. Discovery Service has a special requirement right now, this is not bad when we have `static` number of discovery services planned but will be very difficult in K8s. We need to find if there is a way for when a new discovery service pod is started, it can "gather" all other discovery services pod information and use that to feed `-Dapiml.discovery.allPeersUrls`. REF: https://github.com/zowe/api-layer/blob/master/zowe-install/src/main/resources/component-scripts/start.sh#L66
2. We need a new key/value store for Caching Service on k8s since VSAM data set doesn't exist and zCX doesn't support reading data set directly. Right now I'm thinking to suggest `etcd` but need to find if there are any obvious cons and confirm with team. If we choose etcd, we need to suggest proper way to deploy/add etcd into our cluster (or maybe the customer prefer their own etcd cluster?).
3. Do we need to suggest a sidecar deployment pattern for some components. The sidecar can help on: adding TLS layer to plain http service, adding dynamic discovery service registration. This may simplify the development of component, but without build-in HTTPS service, this may block the component to run on z/OS. If sidecar is a good way, we can think of build a sidecar image.
4. Currently Zowe stores "configs" in "instance.env" (or a yaml file, in discussion). We need a less destructible way to make sure component level compatible when running on z/OS or in container.
  - Issue 1: we shouldn't simply share current config as volume for all containers because our current config may contain the keystore file (without keyring support). We need to extract certificates and keys and store in Secret. Could this change be covered by Zowe "component start" script? Is it safe?
  - Issue 2: if we store some configs into Secret, should we also store other configs into ConfigMap? If we already convert all our configs into YAML format, i think this should be fairly easy and we can make it transparent to component.
5. Investigate differences between starting component on z/OS and container, what changes we need to make on the start script. The planned changes are defined https://github.com/zowe/zowe-install-packaging/issues/1717. Few differences in my mind:
  - Unlike z/OS environment, the image running component may not contain JDK/JRE, and I don't want to enforce JDK/JRE for all Zowe components. The consequence is https://github.com/zowe/zowe-install-packaging/issues/1769 will not work, and we need to find alternative way to parse JSON/YAML files. The best fit is `jq` which is much smaller than JDK/JRE.
  - We should build and ship a tool for components as start command. This command will cover how to read and parse configs and eventually launch component. This will make component start method same as z/OS. We will need design what should be included into this tool and how to ship it.
  - if we require the component to include a version of this tool in component image, what happens if the cluster has several versions of component start tool in same cluster?
  - if we don't require the component to include a version of this tool, could this tool be shipped outside any known component but as independent and then mount to all other components. Or maybe the component should include a simple script to download the component start tool from a common known url like `https://<gateway>:<port>/download-component-start-tool`.
6. Same as packaging on z/OS, we need to provide similar guidance for component to build docker image. These questions should be answered:
  - what base images are suggested
  - i prefer the image to be as small as possible. So if the component doesn't need JDK, it shouldn't be there. If the component is not node.js app, then node.js shouldn't be in the image. If the component is compatible with Alpine Linux, then we should use Alpine.
  - what tool we need to pre-installed into the image (like jq)
  - we may need the component image to include Zowe component launch tool. How to version this toolbox, and how to keep it compatible if the component is using an old version.
  - should we provide official base images to cover some details we pre-req.
  - what will be the folder structure we suggest the user to put into image. Where we mount configs, where the component root folder should be, etc.
  - guidance to add component into Zowe k8s cluster.
  - guidance on versioning, building and releasing docker images
  - This guidance should also apply to build-in components like explorer APIs/UIs.
7. Investigate suggestions for build process changes.
  - How the component should build and ship their own docker images
  - How Zowe should define Helm channel and ship Helm chart in, I suppose, zowe-install-packaging.
  - How Zowe release Helm chart along with current Zowe release process.

@markjhollands if you pick any of the item, please leave a comment. Thank you! And sorry in advance, I may add more research items as we moving forward and have a better understanding.

**Comment by markjhollands** [comment]
Will do @jackjia-ibm 

Quick comment around item 7... in addition to Helm, we need to discuss the use of operators, and to what extent our operator should automate the running in k8s

**Comment by balhar-jakub** [comment]
2. wouldn't it be better to provide MQ support rather than etcd?
3. We provide such enablers for Java within the API ML. You just insert the library and provide config and it will dynamically register. 
6. It is possible to generate optimized Docker containers per API ML service with JIB (https://github.com/GoogleContainerTools/jib).
7. As for the refresh. There is API that reloads the current state for the static file. So it is about how do we get the update to the file. 
   As for deregistration there is a circuit braker within the Gateway which removes the service from the rotation after three successive failures and with the retry it means that it only prolongs the requests but doesn't fail them. But it would help if at some point we implement the health check for the statically registered services. 
8.

**Comment by markjhollands** [comment]
@jackjia-ibm & @balhar-jakub 

2. Aren't etcd and MQ quite different in what they provide? The standard way of providing persistent key/value on Kubernetes is etcd (its what k8s itself uses), the only disadvantage I see is that means we have a different solution for z/OS and for containers, but I think that could be inevitable, and we shouldn't be afraid to have different solutions if it makes sense for the platform.

3. I think the approach @jackjia-ibm suggests could bring some advantages. We could harness technologies like Istio to create a service mesh. Unfortunately, I don't know what we already provide, so would need to check on that.

6. I've never used JIB before, but seen others that try and do the same thing. I think it depends how much control we want / need about how the container is built, for example the base image used. If one of our use cases is OpenShift, I would look at the Red Hat Certified base image: https://catalog.redhat.com/software/containers/search?p=1&vendor_name=Red%20Hat%2C%20Inc.

I have experience problems with Alpine before as it uses musl, not glibc for its C libraries. We also need to really limit the tools we provide in the image, but this may be on a case by case basis.

**Comment by markjhollands** [comment]
Regarding point 1 from @jackjia-ibm - from my understanding we use Netflix Zuul, and the Discovery Service uses Spring Eureka for service discovery. I believe people have already have this running in Kubernetes, but configuration may be slightly different. I believe when you define a service, you have to specify the Kubernetes Service (e.g. ClusterIP service) to route to. Kubernetes should handle most of the load balancing / routing.

**Comment by markjhollands** [comment]
Point 4 from @jackjia-ibm - I would see the use of ConfigMaps and Secrets as essential. Using these standard mechanisms would allow customers to integrate with vaults for secrets as well. We also need to consider (at some point, maybe not or MVP) how we integrate with solutions like cert-manager

**Comment by markjhollands** [comment]
I would also like to elaborate on point 6 as I think this is an important starting point. I mentioned before about using the Red Hat certified, Universal Base Image, based images. Using this base image provides images that run on `s390x` (for zCX and Linux on Z), as well as `amd64`.
From these UBI images, Red Hat then have images for Java and Node.js (as well as many other images) for the different components. This has many advantages like better performance due to image layer caching, certified maintained images, and inherent support from Red Hat if hosted on RHEL or OpenShift (although RHEL or OpenShift is not a prereq).

**Comment by jackjia-ibm** [comment]
Thanks @balhar-jakub @markjhollands 

2. One reason I suggested etcd over MQ here is we can still provide a "free" solution for the hybrid deployment since VSAM is not available. I'm open to any commercial product but would like to have the free tier, so Zowe doesn't look like a up-selling tool for MQ. :)

3. There is difference between sidecar and enabler. The sidecar doesn't really need to change the component itself but the way we organize the pod. This makes easy if the component doesn't want to handle HTTPS and registration, the sidecar can do those for it. For z/OS deployment, HTTPS can be offloaded to AT-TLS and maybe Zowe component start script can potentially do dynamic registration by reading the component manifest. The primary goal is to simplify component development as much as possible. With sidecar, the component can concentrate more on the functionalities it wants to provide, less worry about deployment. But so far in my mind, sidecar is an option, not mandatory for component due to the cost it introduces.

4. Can we run cert-manager on z/OS? But the complicated part for z/OS is we have Keyring I believe it won't be supported anyway, and Keyring is probably the primary method the end-user will care. If we can provide a universal experience regarding certificate management will be ideal but could be too good to be true for now.

7. I'm aware of the functions APIML provides. This item is more about how to use it strategically. For example, when the cluster first started, we have 2 explorer APIs will be started almost at same time. Should we call the refresh api twice after each pod is started? Or can we do just once? If jobs api is scaling to 2 pods, should we call the refresh api again? Who will eventually make the refresh api call? etc.

I've never used JIB before, it's good chance for me to learn. 👍 

The question I asked in #zowe-ha channel is actually related to item 1 though I described in sysplex scenario:

Jack T. Jia  23 hours ago
@Jakub Balhar I have a question related to Discovery Service allPeersUrls property. For example, the deployment planned 2 discovery services and setup allPeersUrls as 2 discovery instances. All good so far. Later on, we add one more LPAR to the sysplex and a new discovery service. Is there a way to refresh the 2 existing discovery services to have 3 peers without restarting them?

Jakub Balhar  23 hours ago
I will have to try. I would expect that when we provide all the remaining servers to the newly added one, all the discovery services should eventually synchronize

**Comment by jackjia-ibm** [comment]
@stevenhorsman @1000TurquoisePogs @Joe-Winchester for your awareness of the discussion undergoing, please feel free to comment.

**Comment by balhar-jakub** [comment]
@jackjia-ibm I was verifying how the discovery service behaves when there are multiple instances and it is ok to provide to the newly added discovery service at least one working discovery service and all the running services eventually synchronizes and knows about each other.

**Comment by balhar-jakub** [comment]
2 - The etcd looks fine. The Caching service is anyway built in such way as to provide simple way to extend for diferent storage solutions. If we later on move to MQ we had ActiveMQ in mind as default as it is open-source and written in Java

3 - Thanks for he distinction and yes, this way it makes sense.

**Comment by jackjia-ibm** [comment]
Related to item 10 but trying to be more specific. We want to make sure the internal certificate works well in k8s. The challenge is pod name and ip are all dynamic. How should we prepare internal certificates SAN and also enable certificate verification, which is mandatory for production environment.

**Comment by jackjia-ibm** [comment]
I think this item can be closed for now as this doc [Zowe_Containerization 21PI2 - OSS.pptx](https://github.com/zowe/zowe-install-packaging/files/6873034/Zowe_Containerization.21PI2.-.OSS.pptx) is prepared.
