### ISSUE TITLE
config workflows not in convenience and SMP/E build

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#1527]
**Describe the bug**
We noticed that the 1.13 and 1.14 SMP/E & convenience install does not include the config workflows `<pathPrefix>/files/workflows/ZWE*.xml`.

**To Reproduce**
convenience
1. extract pax file: `pax -r -px -f zowe.pax`
2. install zowe: `install/zowe-install.sh -h $hlq - i $dir`

SMPE
1. install AZWE001 FMID
2. apply v1.14 PTFs UO01948 and UO01949

In both cases you'll see files/workflows does not exist. A search for ZWEWRF (`find . | grep ZWEWRF`) also comes back empty handed.

**Expected behavior**
workflows must be present after install

**Comment by OnnoVdT** [comment]
Workflows are in zowe.pax, but are not in the installed libraries, so we need a closer look at zowe-install.sh
I also noticed the fingerprint is created before template workflows are created, so we are missing files (JCL and matching workflows).

**Comment by OnnoVdT** [comment]
zowe-install.sh ending with RC on failure 
```
+ /ZOWE/tmp/zowe-packaging-20200723065709/content/zowe-1.14.0/install/zowe-install.sh -i /ZOWE/tmp/zowe-packaging-20200723065709/zowe-runtime -h ZOWEAD3.T397499 -l 
FSUM6614 /ZOWE/tmp/zowe-packaging-20200723065709/content/zowe-1.14.0/install/zowe-install.sh: Option -l argument missing
Invalid option: -?
```

**Comment by John-A-Davies** [comment]
Sounds like we need an automated test that at least verifies that the config workflows are present in the build, and the test should really execute the workflows too, otherwise we are shipping untested code, and it's subject to regression.

The fingerprint is created from an install performed right after the convenience PAX file is generated - that PAX process has not been changed, so the workflow would have been missing from the convenience build before fingerprint was introduced.

**Comment by OnnoVdT** [comment]
Ensuring that the parts are installed is something that must be solved on a broader scale, not specific for the config workflows. I agree that it's best we have an automated testcase that drives toe workflows.
