### ISSUE TITLE
High Availability Research: Cold/Warm Standby

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#1543]
Research possibilities for setup a cold or warm standby of Zowe, and use VIPA to automate switch over.

**Comment by NayerNajafi** [comment]
**1- Cold standby:**
A method of redundancy in which the secondary server is only called upon when the primary fails. The server on cold standby receives scheduled data backups, but less frequently than a warm standby. It can be done by bringing up the new system/service/component (i.e., starting an executable by loading it from media), initializing it, and bringing it into service.
**Usage:** Cold standby is used for non-critical applications or in cases where data is changed infrequently.

**2- Warm standby:**
A method of redundancy in which the secondary (i.e., backup) server runs in the background of the primary. The data is mirrored to the secondary at regular intervals, which means that there are times when both do not contain the exact same data. Repair the service is the same as in Cold standby mode, except the new service is already loaded in memory, and may have some idea of the state of the service that just failed.

**3- Hot standby:**
A method of redundancy in which the primary and secondary run simultaneously. The data is mirrored to the secondary server in real time so that both contain identical information. In this mode the standby server notices immediately when the primary service fails, and takes over. The primary and the standby service are in constant communication. The standby receives updates from the primary every time a significant event occurs.

**Comment by NayerNajafi** [comment]
**Questions and Problems:**
**1-** What should be the time interval (failover time) to achieve any standby mode? after a few seconds, hundred microseconds or milliseconds?
**2-** How the secondary server will be notified of primary failure?
**3-** Does the standby server need to create another copy of itself to feed updates to when it becomes primary, in case it fails?
**4-** Cold standby: It is just startup/initialize for the first time, it will verify the requirements, read the instance.env or configuration file, bind to whatever services it needs.
**5-** Warm standby: It may need to perform further initialization only after it's been activated because it may depend on being able to determine the current state of the server before it can service requests.
**6-** Hot standby: It may need to actively monitor the health of its primary process, this could be anything from establishing
a connection to the primary process and blocking until it dies. So, it may involve more complex heuristics.

**Comment by jackjia-ibm** [comment]
With investigation and discussion, cold/warm standby seems are not interests of us. We will focus on Active-Active HA mode.
