### ISSUE TITLE
should scripts/utils/zowe-install-*.sh be in bin/ ?

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#1549]
**Describe the bug**
zowe-install-proc.sh and zowe-install-xmem.sh are currently hidden away in scripts/utils/, but are required setup steps and thus belong in bin/.

**Expected behavior**
Move scripts/utils/zowe-install-*.sh to bin/. This does require some adjustments inside the scripts to determine the value of ZOWE_ROOT_DIR.

**Comment by stevenhorsman** [comment]
So being pendantic, I think they aren't technically required setup steps. I think our documentation suggestions doing these updates manually (as we've had feedback from lots of customers that they would never let any automated script update their JES2 concatenated libraries), but offers the automated scripts for convenience in pipeline situations. @Joe-Winchester is this correct?
However I agree that for consistency they should be moved to bin/utils, but have been advised to keep them in `scripts/utils` in order to comply with LTS, as they are documented scripts and therefore could be argued as 'SPI'. Admittedly given that you updated one of these this week maybe the rules have changed.

**Comment by Joe-Winchester** [comment]
Yes the scripts for copying the load member and proc lib are only really intended for customers building pipelines - I've actually rewritten the docs-chapter for install-xmem in 1.14 so the scripts aren't mentioned in the install main chapter now and are in a separate chapter on pipeline (customers were getting confused as this was based on direct feedback).  I think we should leave things as they are, especially as moving them would be a breaking change for anyone who had built a pipeline using them which goes against LTS being stable.
