### ISSUE TITLE
ZWEKRING JCL failed RC 12 with "IEC020I 001-4,ZWEKRING,RUN,SYSTSIN,JES"

### ISSUE THREAD

**Issue by rjmaomao** [zowe/zowe-install-packaging#1666]
Hello,

I installed 1.15.0 runtime, updated ZWEKRING member in SZWESAMP data set. I used default option, only updated values such as HOSTNAME,IPADDRES,ZOWERING etc.  Submit the JCL, it failed with RC 12. 

I saw following message in job log. 
 _IEC020I 001-4,ZWEKRING,RUN     ,SYSTSIN ,JES      
 IEC020I EROPT IS 'ABE' OR NOT SPECIFIED_           

 _IKJ56600I UNRECOVERABLE COMMAND SYSTEM ERROR_

Can't figure out what is wrong here, could you please help to take a look?  Thanks!

[RENJING.ZWEKRING.LOCA.D092220.log](https://github.com/zowe/zowe-install-packaging/files/5261077/RENJING.ZWEKRING.LOCA.D092220.log)

**Comment by vit-tomica** [comment]
The JCL failed because a substitution done at [this line](https://github.com/zowe/zowe-install-packaging/blob/b630308db85568d208a01560184341475b05f030/files/jcl/ZWEKRING.jcl#L168) caused the line to exceed the allowable length. It's a comment line, so as a workaround you can delete the line to make it work. 

I see you use a different value here:
```
SET ZOWERING='ZoweKeyring.LOCALCA.Z2'                                                                      
```
Please use the same value that you used for the first time. You just need [these commands](https://github.com/zowe/zowe-install-packaging/blob/b630308db85568d208a01560184341475b05f030/files/jcl/ZWEKRING.jcl#L140-L158) to be executed. The rest can be commented out. 
If this is confusing then you can start from the beginning. Use the https://github.com/zowe/zowe-install-packaging/blob/master/files/jcl/ZWENOKYR.jcl to clean up your current setup.

**Comment by rjmaomao** [comment]
@vit-tomica Hi Vit, thank you for your instruction. I use a different keyring name because I want to differentiate local ca keyring with external ca keyring. After deleting the comment line, I was able to get a RC 00 code, and Zowe server start successfully. I didn't know the substitution happens even in comments. It very likely customer would update the default value to fit their need. Is there any way to not substitute variable in comments?

I have another question about keyring. If I have multiple zowe version and multiple instances running on same system, do I need multiple keyring and certificates? On what level should the keyring be used? Can it be shared with system level, like one keyring for one system? Or Zowe version level? Instance level?  And the same question for  jwtsecrete certificates, do I need multiple jwt certificates if I have multiple zowe version and instances?

Thanks.

**Comment by vit-tomica** [comment]
@rjmaomao Hi Jing, I'm glad to hear that it worked. You are right that this will likely happen to someone else. It has to be fixed. I'm not sure if the substitution can suppressed but I could replace the snippet `CONNECT(ID(&ZOWEUSER.) LABEL('&LABEL.')` with `CONNECT(ID(ZOWEUSER) LABEL('LABEL')`. Removing the `&` character removes the substitution. On the other hand, the snippet will not perfectly match the actual [security command](https://github.com/zowe/zowe-install-packaging/blob/b630308db85568d208a01560184341475b05f030/files/jcl/ZWEKRING.jcl#L218). What do you think?

Regarding the question about multiple Zowe versions, instances etc. A keyring is always attached to a specific userid (ACID) so technically you can run more Zowe instances or versions (if a specific Zowe version supports keyrings) under the same ACID, keyring and certificate just fine. I think nothing prevents you to create another keyring with a different certificate if you require that. As far as I know, we do not provide any recommendation on this. If you have systems in a sysplex that share security database, you can use the keyring and certificate across the sysplex as well. The same applies to the jwtsecret which is an item in a keyring.

**Comment by vit-tomica** [comment]
fixed
