### ISSUE TITLE
Integrate new springboot based jobs app into install

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#206]
Depends on https://github.com/zowe/jobs/issues/15
Depends on https://github.com/zowe/jobs/issues/9

Pull down the assets from artifactory
Add a new port for the app into the yaml
share the api ml certificate with the app
Create a script to start the jar and call this from zowe-start?
What else?

**Comment by jackjia-ibm** [comment]
@stevenhorsman @Joe-Winchester the changes have been put in branch `issue-206`. I and Nayer had tested the build `libs-snapshot-local/com/project/zowe/0.9.6-ISSUE-206/zowe-0.9.6-20190104.185906-11.pax` and found there are 2 things:

1. With the first run of `zowe-install.sh`, it gives error on creating target folder `explorer-jobs-api`. Error message looks like this:

```
Installing Explorer API into /u/zowesvr/explorer-*-api ...
Installing Explorer Jobs API into /u/zowesvr/explorer-jobs-api ...
mkdir: FSUM6404 directory "scripts": EDC5129I No such file or directory.
cd: /u/zowe-0.9.6/install/..//scripts/zowe-explorer-api-install.sh 51: .: zowe-i
nstall.sh 92: scripts: EDC5129I No such file or directory.
```

But if re-run the install without change anything, this error won't show up again, even though re-login to shell. So I'm confused what happened. Please try if you see the same error.

2. After installation, jobs tomcat server is successfully started on port 8545. But if visiting https://<server>:8545/api/v1/jobs, it cannot login with correct password on Nayer's machine, but works well on river. Please see if you have similar error.

Otherwise I think the `issue-206` branch is ok to marge to master.

**Comment by jackjia-ibm** [comment]
This has been done with PR https://github.com/zowe/zowe-install-packaging/pull/229
