### ISSUE TITLE
Containerization Spike: investigate certification requirements

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#2170]
There are several certification programs out in market. Investigate what requirements/rules are applicable for Zowe.

- OCI compliance – should we care about it, or anything special rules we need to follow
- [Docker Certified publisher and images](https://docs.docker.com/docker-hub/publish/certify-images/)
- [Red Hat Container Certification](https://connect.redhat.com/en/partner-with-us/red-hat-container-certification)
- [IBM Cloud Pak Certification](https://playbook.cloudpaklab.ibm.com/requirements-by-type/) extract items we need to follow

Expected Result: checklist of rules in these categories
- OCI compliance
- Docker Certified images
- Red Hat Container Certification
- IBM Certification
- Zowe conformance recommendation
- Zowe conformance requirement

**Comment by CarsonCook** [comment]
# OCI Specifications

Workflow that allows users to ru nan image with no additional arguments.

An OCI implementation downloads the OCI image and unpacks it into an OCI Runtime filesystem bundle and is ran by the OCI runtime.

Summary of requirements:
* [Image manifest](#image-manifest) that references image contents and dependencies.
* [Image layers](#image-layer) that describe the container filesystem.
* [Image configuration](#image-configuration) that describes how an image is executed as a container.
* [Container configuration](#container-configuration) that describes how a container implements standard operations.
* Adherence to specific [container lifecycle requirements](#lifecycle).
* Support of [standard container operations](#operations).

## Image Specification

Contains sufficient information to launch the applicaton on the target platform. Create an OCI image that contains an image manifest, layer serialization, and image configuration.

### Image Index

Higher level manifest that points to specific image manifests ideal for certain platforms. OPTIONAL.

Follow the below structure. Fields are required unless notes otherise. Further details and other optional fields are [here](https://github.com/opencontainers/image-spec/blob/master/image-index.md).
```json
{
    "schemaVersion": 2, // must be 2
    "manifests": [ // May be an empty array
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "size": 123, // number of bytes of the raw content
            "digest": "sha256:hex", //digest of the content
            "platform": { // the platform field/object is optional
                "architecture": "ppc64", // Required if platform object exists - the CPU architecture the image is built to run on, should use architecture values listed here: https://golang.org/doc/install/source#environment
                "os": "aix", // Required if platform object exists - the operating system the image is built to run on, should use OS values listed here: https://golang.org/doc/install/source#environment
            }
        }
    ]
}
```

### Image Manifest

Contains metadata about the contents and dependencies of the image.

* Content-addressable images - configuration can be hashed to a unique ID
* Fat manifest that references manifests for platform specific versions
* Translatable to OCI Runtime Specification

Follow the below structure. Fields are required unless notes otherise. Further details and other optional fields are [here](https://github.com/opencontainers/image-spec/blob/master/manifest.md).
```json
{
    "schemaVersion": 2, // must be 2
    "config": {
        "mediaType": "application/vnd.oci.image.config.v2+json",      
        "size": 123, // the number of bytes of the raw content
        "digest": "sha256:hex" // digest of the content
    },
    "layers": [
        
    ]
}
```
### Image Layer

A layer is a tar archive with serialized changes to be made to the filesystem.

* Must be packaged in a tar archive with no duplicate file path entries.
* Initial root filesystem is the base layer
* tar archive is created with the changeset that is applied with the new layer it represents
    * If a target path in a layer changeset already exists:
    * If both are directories, existing path's attributes must be replaced with changeset's attributes. Otherwise;
    * Remove the file path and;
    * Recreate the file path with the contents and attributes of the changeset entry
* If a path is to be deleted, a whiteout file is needed
    * Prefix .wh. on the basename of the path to be deleted
    * Must only apply to resources in layers, nothing outside of a layer

### Image Configuration

Specification for the JSON that describes how images are used with a container runtime and execution tool.
Layers need to be packed and unpacked reproducibly so the DiffId doesn't change.
This JSON is immutable because it is hashed to make an image ID used to make it content-addressable.

Follow the below structure. Fields are required unless notes otherise. Further details and other optional fields are [here](https://github.com/opencontainers/image-spec/blob/master/config.md).
```json
{
    "architecture": "ppc64", // the CPU architecture the image is built to run on, should use architecture values listed here: https://golang.org/doc/install/source#environment
    "os": "aix", // the operating system the image is built to run on, should use OS values listed here: https://golang.org/doc/install/source#environment
    "config": { // OPTIONAL, but if not supplied then execution parameters should be specified at the creation of the container
        // all of these fields are OPTIONAL
        // all can be merged/replaced with value specified when the container is created
        "User": "root", // the user processes run as
        "ExposedPorts": { // set of ports to expose in the container
            "8080/tcp": {}, // map to empty object
            "8000/udp": {},
            "8888" : {} // defaults to tcp
        },
        "Env": [ // array of strings that set environment variables
            "FOO=bar"
        ],
        "EntryPoint": [ // array of strings that list the arguments used by the execution command when the container starts
            "/bin/app"
        ],
        "Cmd": [ // array of strings that list the default arguments to the container entry point. If EntryPoint is not set, first entry is the excutable to run
            "--config",
            "/etc/app/config.cfg"
        ],
        "Volumes": { // directories where the process is likely to write data specific to a container instance
            "/var/app": {} // map to empty object
        },
        "WorkingDir": "/home/app", // string that sets the current working directory of the entrypoint process in the container
    },
    "rootfs": { // rootfs key references to the layer content addresses used by the image
        "type": "layers", // must be layers - must generate error if not set to layers
        "diff_ids": [ // layer content hashes in order from first to last
            "sha256:hex" // DiffId is the digest over the layer's uncompressed tar archive
        ]
    }
}
```

## Runtime Specification

The Runtime Specifciation outlines how to run an unpacked OCI image.

### Container Configuration

The container's root filesystem must be in the container bundle. This is what is referenced by `config.json` `root.path`.

`config.json` file must be in the root of the bundle directory. It contains metadata needed to implement standard operations against the container.

Follow the below structure. Fields are required unless notes otherise. Further details and other optional fields are [here](https://github.com/opencontainers/runtime-spec/blob/master/config.md).
```json
{
    "ociVersion": "1.1", // OCI version the runtime is compatible with
    "root": { // Required unless this is for a Hyper-V container, in which this field cannot be included
        "path": "/bundle", // On POSIX an absolute or relative path to the bundle, on windows a volume GUID path
    },
    "mounts": [ // Optional - additional mounts beyond the root object
        {
            "destination": "/container-folder", // required in a mount object - destination of the mount point, path inside a container
            "source": "/host-folder" // Optional - file or directory for the bind mount, absolute path or relative to the bundle
        }
    ],
    "process": { // Optional, but required for the start command to be called
        "cwd": "/", // Working directory for the executable. Must be an absolute path
        "env": [ // Optional - specifies environment variables as an array of strings
            "FOO=bar"
        ],
        "args": [ // At least one entry if not Windows
            "sh"
        ],
        "commandLine": "cmd", // full command line to be execute on Windows. required if no args field
        "user": { // controls what user the process runs as
            "uid": 1, // POSIX required - user ID
            "gid": 1, // POSIX required - group ID
            "username": "user" // Windows only, optional
        }
    }
}
```

### Lifecycle of a Container

#### State

The state of a container must follow the below structure. Fields are required unless notes otherise. Further details and other optional fields are [here](https://github.com/opencontainers/runtime-spec/blob/master/config.md).
```json
{
    "ociVersion": "1.1", // semantic version of the OCI runtime spec that the state complies with
    "id": "123abc", // the containers ID
    "status": "created", // runtime state of the container, may be one of: creating, created, running, stopped. Different status values can be used but must mean something different
    "pid": "123", // Required on Linux when the status is created or running, otherwise optional. ID of the container process
    "bundle": "/mybundle", // absolute path to the container's bundle directory
}
```
 
#### Lifecycle

The lifecycle describes the timeline of events that happen from when a container is created to when it ceases to exist.

Hooks mentioned below are lifecycle hooks that enable custom actions to be configured in `config.json`.

* OCI compliant runtime's create command is invoked with a reference to the location of the bundle and a unique identifier.
* The container's runtime environment MUST be created according to the configuration in config.json. If the runtime is unable to create the environment specified in the config.json, it MUST generate an error. While the resources requested in the config.json MUST be created, the user-specified program (from process) MUST NOT be run at this time. Any updates to config.json after this step MUST NOT affect the container.
* The prestart hooks MUST be invoked by the runtime. If any prestart hook fails, the runtime MUST generate an error, stop the container, and continue the lifecycle at step 12.
* The createRuntime hooks MUST be invoked by the runtime. If any createRuntime hook fails, the runtime MUST generate an error, stop the container, and continue the lifecycle at step 12.
* The createContainer hooks MUST be invoked by the runtime. If any createContainer hook fails, the runtime MUST generate an error, stop the container, and continue the lifecycle at step 12.
* Runtime's start command is invoked with the unique identifier of the container.
* The startContainer hooks MUST be invoked by the runtime. If any startContainer hook fails, the runtime MUST generate an error, stop the container, and continue the lifecycle at step 12.
* The runtime MUST run the user-specified program, as specified by process.
* The poststart hooks MUST be invoked by the runtime. If any poststart hook fails, the runtime MUST log a warning, but the remaining hooks and lifecycle continue as if the hook had succeeded.
* The container process exits. This MAY happen due to erroring out, exiting, crashing or the runtime's kill operation being invoked.
* Runtime's delete command is invoked with the unique identifier of the container.
* The container MUST be destroyed by undoing the steps performed during create phase (step 2).
* The poststop hooks MUST be invoked by the runtime. If any poststop hook fails, the runtime MUST log a warning, but the remaining hooks and lifecycle continue as if the hook had succeeded.

#### Operations

Runtimes must support:
* state <container-id> - query the state. Generate an error if the ID is not provided. Return a container state object as seen [here](#lifecycle).
* create <container-id> <path-to-bundle> - create a container. Generate an error if ID or bundle are not provided or if the ID is not unique. Apply properties in `config.json`, all but `process` must be applied.
* start <container-id> - start a created container. Generate an error if no ID is provided or if the container is not created. Must run the program specified via `process` in `config.json`. Generate an error if `process` is not set.
* kill <container-id> <signal> - stop a container and send the given signal to the container process. Generate an error if the ID is not provided or if the container is not created or running.
* delete <container-id> - delete a created container. Generate an error if no ID is provided or the container is not stopped. Deleting the ocntainer must delete resources created in the `create` step.

**Comment by CarsonCook** [comment]
# Red Hat

Summary of Zowe related takeaways from RedHat certification requirements:
* Require a specific deployment tool/method (e.g. Helm) and specific elements/properties of that deployment tool/method
* Require verification of functionality on the target platform
* Require a certain base image
* Require licenses be included in the image
* Requirement descriptive labels in the Dockerfile
* Require a maintenance process to ensure image security

Summary of RedHat certification requirements. Details  of certification requirements [here](https://redhat-connect.gitbook.io/partner-guide-for-red-hat-openshift-and-container/):
* Deploy with Helm or deploy with an Operator
* Verify product functionality on the target Red Hat platform
* Include relevant licenses in `licenses/` directory of container images
* Bases image must be or be based on a supported Red Hat image
* Maintain the image health:
    * Red Hat continuously scans images for vulnerability and assigns a grade
    * When grade falls below A, a notification is sent to the maintainer
    * Unclear what else happens, and when
* Dockerfile must have labels `name`, `maintainer`, `vendor`, `version`, `release`, `summary`, `description`
* Requirements for Helm charts:
    * Functionality must bee tested on OpenShift
    * Product must be supported on OpenShift
    * All containers used by the chart must be Red hat certified containers
    * Chart must be compatible with Helm 3 (apiVersion v2)
    * Chart must contain a `README.md` file
    * Chart must set the kubeVersion field to indicate the minimum Kubernetes version supported
    * Chart must include one or more tests in the `templates` directory to verify successful installation
    * Chart must include a `values.yaml` and a `values.json` file to identify inputs and provide validation
    * Chart should not contain any custom resource definitions
    * Chart must pass the `helm lint` command
    * [chart-verifier](https://github.com/redhat-certification/chart-verifier) is an open source tool used to verify a Helm chart against Red Hat certification requirements and recommendations

**Comment by CarsonCook** [comment]
# Docker Verified Publisher

From the support team:
```
The only criteria is that your company is an Independent Software Vendor and looking to distribute software through Docker. This is a new program so our resources are limited, however, we are happy to set up a call to walk you through our slides we share to partners who are interested. 
```

**Comment by CarsonCook** [comment]
# Miscellaneous Tips:
* Use UBI where possible
* Don't run as root within the image
* Scan imaes regularly
    * Artifactory does some scanning but anchore is a CLI that is good for a quick test
    * Anchore command: `curl -s https://ci-tools.anchore.io/inline_scan-latest | bash -s -- Image_to_scan_here` (image has to exist locally)
* Can remove some CVEs by removing certain packages from the UBI base image
* RedHat dropped Docker support in RHEL 8

**Comment by jackjia-ibm** [comment]
Consolidate various investigation and discussion, this will be the conformance criteria related to containerization: https://github.com/zowe/zowe-install-packaging/pull/2220
