### ISSUE TITLE
STDOUT gives "Unable to retrieve content" from JOBS UI

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#237]
I tried to view the STDOUT file for a large job.  It has > 1.5 M lines.

**Comment by Joe-Winchester** [comment]
@John-A-Davies - This should be in the repository for jobs rather than install-packaging.  Can I close this here and you re-open it in either the jobs repository (if it fails in the swagger for the get content - you can get at this by clicking through the z/OS JES service from the API catalog file) or else in the explorer-jes repository if it is a UI failure.  Can you also include what goes wrong and how to re-create, e.g. the name of the job you used if it's one we can find on 3b to re-create.  Tks

**Comment by John-A-Davies** [comment]
Yes, close here and I'll re-open in jobs.  I guess any job that big is what does it.
