### ISSUE TITLE
zwe positional statement syntax unclear

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zowe-install-packaging#2574]
When I executed `./zwe init --update-config --allow-overwritten apfauth` I thought I would just be doing the `apfauth` step, but instead the entire init was done.
The correct command appears to be  `./zwe init apfauth --update-config --allow-overwritten`
`zwe init --help` doesn't show what the syntax should be, so it seems like we need to enhance the help a bit, or enhance the argument reading. one or the other.

In `man` output, command format is the first line shown. We could follow that standard.

Such as if the help said:

```
  Format

  zwe init [sub-command] [option [option]...]

  Example

  zwe init certificate -v -l /my/log/output


------------------
Global parameters:
  --help|-h: boolean, optional
    Display this help.
  --debug|--verbose|-v: boolean, optional
    Enable verbose mode.
  --trace|-vv: boolean, optional
    Enable trace level debug mode.
  --log-dir|--log|-l: string, optional
    Write logs to this directory.
  --config|-c: string, optional
    Path to Zowe configuration zowe.yaml file.

------------------
Parameters for command "init":
  --allow-overwritten: boolean, optional
    Allow overwritten existing MVS data set.
  --skip-security-setup: boolean, optional
    Whether should skip security related setup.
  --security-dry-run: boolean, optional
    Whether to dry run security related setup.
  --update-config: boolean, optional
    Whether to update YAML configuration file with initialization result.

------------------
Available sub-command(s):
  - apfauth
  - certificate
  - mvs
  - security
  - stc
  - vsam
```

**Comment by jackjia-ibm** [comment]
We can improve the help message here, but so far I cannot find a better way to allow this format `./zwe init --update-config --allow-overwritten apfauth`.

The reason is some arguments, whether it's a boolean or string, are confirmed after a sub-command is identified. For this command, `./zwe init --update-config --allow-overwritten apfauth`, without going through the parameters of sub-commands one by one, just based on looking at the command, it's hard to say `apfauth` is a sub-command, or the value of `--allow-overwritten`. The parser must know the sub-commands first, then it can be sure `--allow-overwritten` is a boolean argument, it doesn't take a value.

**Comment by adityadr-joy** [comment]
https://github.com/zowe/zowe-install-packaging/pull/2640
