### ISSUE TITLE
Should we rename `zowe.setup` to `zowe.init`

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#2653]
Currently `zowe.setup` is mainly used by `zwe init` command. Renaming it to `zowe.init` may make it more clear that this section is related to which command.

Thoughts:
- `zowe.setup` could be used by other commands, like `zwe install` and `zwe init`
- `zwe init` command also reads other sections, like `components.caching-service.storage.vsam.name`. This is the case that this configuration is also required by runtime. `zwe init` may also update sections not in `zowe.setup`.

**Comment by DivergentEuropeans** [comment]
I took a quick glance at this & install command (your shell script comments are pretty good, thanks for doing that btw!), because of your notes in "thoughts" @jackjia-ibm It's probably not a good idea to do this by confusing people unless we have a 1:1 relationship ie. install reads MVS section to read datasets in zowe.setup and creates new ones if applicable. Maybe it would be useful to code out some of those edgecases, but unsure if the work involved is useful to the user outside more intuitive naming or near the priority of other tasks

With the mvs, security, and certificate categories, it sounds like a good idea may be to just rename `zowe.setup` to `zowe.configuration` or `zowe.config`. What do you think?

**Comment by jackjia-ibm** [comment]
Pending more discussion, will not happen in `v2.0.0-TP1`.

**Comment by jackjia-ibm** [comment]
After discussion, we think should remain as-is until we come with better word.
