### ISSUE TITLE
opercmd script is not executable in install directory of Zowe 1.0 nightly

### ISSUE THREAD

**Issue by kathysychan** [zowe/zowe-install-packaging#266]
We installed the Zowe 1.0 nightly driver 1.0.0-20190114.234714-388 and found that the opercmd.sh script in the install/script directory does not have execution bits turned on. This cause the install to fail and thus a major issue. This did not happen when we install build 377 from yesterday.

I just noticed that @John-A-Davies had a similar issue (#203) opened and fixed it a few weeks ago.

@jackjia-ibm, do you run into this problem as well in your CI/CD pipeline?

**Comment by John-A-Davies** [comment]
Which script failed?  The LOG_FILE should tell you.  If you always run `zowe-check-prereqs.sh` first, it adds execute permission to that file, but if you run `zowe-api-mediation-configure.sh` first, it will fail.

**Comment by John-A-Davies** [comment]
@jackjia-ibm is there a process in the build that sets file permissions, so that the expanded PAX file result in `/scripts/opercmd` is set to be executable?  Or is that done for only files suffixed by `.sh` ?

**Comment by jackjia-ibm** [comment]
@John-A-Davies @kathysychan during packaging, `opercmd` is not set to executable. It wasn't an issue before because we don't run `opercmd` during installation. But now I think we need to set it at the end of `pax-workspace/pre-packaging.sh` file where we add `x` to shell scripts.

This didn't become an issue in our test environment because we run `zowe-check-prereqs.sh` for each installation.

In `zowe-check-prereqs.sh`, imo we should remove any "change" or "update" on the system. The file name says "check" and this step is not mandatory to Zowe installation.

**Comment by John-A-Davies** [comment]
Shall we set it at the end of pax-workspace/pre-packaging.sh, then?

**Comment by jackjia-ibm** [comment]
This has been resolved by https://github.com/zowe/zowe-install-packaging/pull/268
