### ISSUE TITLE
Installation of API ML extension don't preserve extended attributes

### ISSUE THREAD

**Issue by pablocarle** [zowe/zowe-install-packaging#2711]
**Describe the bug**

Extension can provide native libraries (*.so) and these may require program controlled attributes, set for example with the following command:

```
extattr +p *.so && chmod a+x *.so
```

```
  p
           When this attribute is set (+p) on an executable program file (load
           module), it causes the program to behave as if an RDEFINE had been done
           for the load module to the PROGRAM class. When this program is brought
           into storage, it does not cause the environment to be marked dirty.

           To be able to use the extattr command for the +p option, you must have
           at least read access to the BPX.FILEATTR.PROGCTL resource in the
           FACILITY class. For more information about BPX.FILEATTR.PROGCTL, see
           Commonly used environment variables in z/OS UNIX System Services
           Planning.
```

**To Reproduce**
1. Install Zowe v2 convenience build with the provided sample extension enabled (sample extension: https://github.com/zowe/api-layer/tree/master/apiml-sample-extension-package)
2. Under `<extensionDirectory>/apiml-sample-extension/bin` change extended attribute of one of the files.
3. Start Zowe
4. Verify the extension was successfully installed, the directory structure inside the workspace should resemble:
.../sharedLibs/org.zowe.apiml.sdk.apiml-sample-extension-package
    bin/
         archive.jar
5. Verify extended attributes of the copied binary files with `ls -E`

**Expected behavior**
- Installation scripts should make sure the extended attributes are preserved in the copy.
- An alternative would be to allow custom post-installation commands for the extensions.

**Comment by jalel01** [comment]
@jackjia-ibm please could you let us know if this will be addressed ahead of v2 GA. If not we'll need to explore workarounds and document limitations. Thank you.

**Comment by jackjia-ibm** [comment]
@pablocarle @jalel01 I misunderstood about the attribute you were talking about, i was thinking about encoding.

You are right, because of the variety of extensions, different extensions may have different expectation on the attribute, so this is actually suggested to be handled by the extension itself by defining `commands.install` in package manifest. Or maybe ship as pax package.

Here is an example of how zss handles it:

- Defining `commands.install` like this https://github.com/zowe/zss/blob/v1.x/staging/manifest.template.yaml#L26
- Then set attribute https://github.com/zowe/zss/blob/v1.x/staging/bin/internal-install.sh#L3

Zss is not expected to run off-Z, but for extensions which can run off-Z, an extra platform check will be great.

In v1, just use `if [ `uname` = "OS/390" ]; then` to check platform.
In v2, can use `if [ "${ZWE_RUN_ON_ZOS}" = "true" ]; then` to check platform.

**Comment by pablocarle** [comment]
@jackjia-ibm Hi Jack, I tried this option with `commands.install` defined in the extension manifest but I cannot see evidence that this command is being executed. Could it be that it is being executed before the files are being copied to the gateway `sharedLibs` directory?

If this is the case maybe other hooks like `commands.start` or `commands.validate` might be best suited for this?

**Comment by pablocarle** [comment]
I tested it again and `commands.configure` seems to be a good location to set up the attributes. I will close this ticket as no change is necessary from the installation perspective. Thank you.
