### ISSUE TITLE
Profile, analyse and improve zwe command and zowe start performance

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#2825]
Comparing to v1, starting Zowe v2 consumes much more time.

**Comment by jackjia-ibm** [comment]
## Analysing ZWE1SV log

- Test url: https://github.com/zowe/zowe-install-packaging/runs/6169841835?check_suite_focus=true#step:19:25902
- test build Zowe v2.0.0
- v2.x/staging#970 (b4bfbe9fd1f040b67a46eedc442e2a07149a6500)
- totals:
  * 1m21s to global validations started
  * 2m16s to global validations done
  * 8m20s to component validations done
  * 15m39s to component configurations done
  * 16m34s to start components
  * 22m55s to all components started

## Key timestamps

- 2022-04-26 05:31:44 <ZWELNCH:16845366> ZWESVUSR INFO ZWEL0021I Zowe Launcher starting
- 2022-04-26 05:32:15 <ZWELS:67285> ZWESVUSR INFO (zwe-internal-start-prepare:337) Zowe version: v2.0.0
  * (+31s) zwe kicks in
- 2022-04-26 05:32:22 <ZWELS:67285> ZWESVUSR DEBUG (zwe-internal-start-prepare,prepare_workspace_directory:36) initialize .instance-s0w1.env(s)
  * (+7s) from last
- 2022-04-26 05:32:27 <ZWELS:67285> ZWESVUSR TRACE (bin/libs/config.sh,generate_instance_env_from_yaml_config:17) Reading /ZOWE/instance/zowe.yaml ...
  * (+5s) from last
- 2022-04-26 05:33:05 <ZWELS:67285> ZWESVUSR TRACE (zwe-internal-start-prepare:370) >>> all environment variables
  * (+38s) from last
  * (+50s) from zwe kicks in
  * (+1m21s) from beginning

### global validate stage

- 2022-04-26 05:33:43 <ZWELS:67285> ZWESVUSR INFO (zwe-internal-start-prepare,global_validate:1) process global validations ...
  * (+38s) from last
- 2022-04-26 05:34:00 <ZWELS:67285> ZWESVUSR INFO (zwe-internal-start-prepare,global_validate:40) global validations are successful
  * (+17s) from last
  * (+1m45s) from zwe kicks in
  * (+2m16s) from beginning

### component validate stage

- 2022-04-26 05:34:02 <ZWELS:67285> ZWESVUSR INFO (zwe-internal-start-prepare,validate_components:1) process component validations ...
  * (+2s) from last
- 2022-04-26 05:34:03 <ZWELS:67285> ZWESVUSR TRACE (zwe-internal-start-prepare,validate_components:7) - checking api-catalog
  * (+1s) from last
- 2022-04-26 05:34:39 <ZWELS:67285> ZWESVUSR TRACE (zwe-internal-start-prepare,validate_components:7) - checking apiml-sample-extension
  * (+36s) from last
- 2022-04-26 05:34:44 <ZWELS:67285> ZWESVUSR TRACE (zwe-internal-start-prepare,validate_components:7) - checking app-server
  * (+5s) from last
- 2022-04-26 05:35:14 <ZWELS:67285> ZWESVUSR TRACE (zwe-internal-start-prepare,validate_components:7) - checking caching-service
  * (+30s) from last
- 2022-04-26 05:35:50 <ZWELS:67285> ZWESVUSR TRACE (zwe-internal-start-prepare,validate_components:7) - checking discovery
  * (+36s) from last
- 2022-04-26 05:36:26 <ZWELS:67285> ZWESVUSR TRACE (zwe-internal-start-prepare,validate_components:7) - checking explorer-jes
  * (+36s) from last
- 2022-04-26 05:36:31 <ZWELS:67285> ZWESVUSR TRACE (zwe-internal-start-prepare,validate_components:7) - checking explorer-mvs
  * (+5s) from last
- 2022-04-26 05:36:36 <ZWELS:67285> ZWESVUSR TRACE (zwe-internal-start-prepare,validate_components:7) - checking explorer-uss
  * (+5s) from last
- 2022-04-26 05:36:42 <ZWELS:67285> ZWESVUSR TRACE (zwe-internal-start-prepare,validate_components:7) - checking files-api
  * (+6s) from last
- 2022-04-26 05:37:20 <ZWELS:67285> ZWESVUSR TRACE (zwe-internal-start-prepare,validate_components:7) - checking gateway
  * (+38s) from last
- 2022-04-26 05:37:55 <ZWELS:67285> ZWESVUSR TRACE (zwe-internal-start-prepare,validate_components:7) - checking jobs-api
  * (+35s) from last
- 2022-04-26 05:38:33 <ZWELS:67285> ZWESVUSR TRACE (zwe-internal-start-prepare,validate_components:7) - checking zss
  * (+38s) from last
- 2022-04-26 05:39:04 <ZWELS:67285> ZWESVUSR DEBUG (zwe-internal-start-prepare,validate_components:41) component validations are successful
  * (+31s) from last
  * **(+5m2s) from process component validations**
  * (+7m49s) from zwe kicks in
  * (+8m20s) from beginning

### component configure stage

- 2022-04-26 05:39:05 <ZWELS:67285> ZWESVUSR INFO (zwe-internal-start-prepare,configure_components:1) process component configurations ...
  * (+1s) from last
- 2022-04-26 05:39:10 <ZWELS:67285> ZWESVUSR DEBUG (zwe-internal-start-prepare,configure_components:22) - configure api-catalog
  * (+5s) from last
- 2022-04-26 05:39:35 <ZWELS:67285> ZWESVUSR DEBUG (zwe-internal-start-prepare,configure_components:22) - configure apiml-sample-extension
  * (+25s) from last
- 2022-04-26 05:40:01 <ZWELS:67285> ZWESVUSR DEBUG (zwe-internal-start-prepare,configure_components:22) - configure app-server
  * (+26s) from last
- 2022-04-26 05:42:19 <ZWELS:67285> ZWESVUSR DEBUG (zwe-internal-start-prepare,configure_components:22) - configure caching-service
  * (+2m18s) from last
- 2022-04-26 05:42:42 <ZWELS:67285> ZWESVUSR DEBUG (zwe-internal-start-prepare,configure_components:22) - configure discovery
  * (+23s) from last
- 2022-04-26 05:43:04 <ZWELS:67285> ZWESVUSR DEBUG (zwe-internal-start-prepare,configure_components:22) - configure explorer-jes
  * (+22s) from last
- 2022-04-26 05:43:28 <ZWELS:67285> ZWESVUSR DEBUG (zwe-internal-start-prepare,configure_components:22) - configure explorer-mvs
  * (+24s) from last
- 2022-04-26 05:43:52 <ZWELS:67285> ZWESVUSR DEBUG (zwe-internal-start-prepare,configure_components:22) - configure explorer-uss
  * (+24s) from last
- 2022-04-26 05:44:17 <ZWELS:67285> ZWESVUSR DEBUG (zwe-internal-start-prepare,configure_components:22) - configure files-api
  * (+25s) from last
- 2022-04-26 05:44:39 <ZWELS:67285> ZWESVUSR DEBUG (zwe-internal-start-prepare,configure_components:22) - configure gateway
  * (+22s) from last
- 2022-04-26 05:45:01 <ZWELS:67285> ZWESVUSR DEBUG (zwe-internal-start-prepare,configure_components:22) - configure jobs-api
  * (+22s) from last
- 2022-04-26 05:45:23 <ZWELS:67285> ZWESVUSR DEBUG (zwe-internal-start-prepare,configure_components:22) - configure zss
  * (+22s) from last
- 2022-04-26 05:47:23 <ZWELS:67285> ZWESVUSR DEBUG (zwe-internal-start-prepare,configure_components:116) component configurations are successful
  * (+2m) from last
  * **(+8m18s) from process component configurations**
  * (+15m8s) from zwe kicks in
  * (+15m39s) from beginning
- 2022-04-26 05:47:24 <ZWELS:67285> ZWESVUSR INFO (zwe-internal-start-prepare:387) Zowe runtime environment prepared
  * (+1s) from last
- 2022-04-26 05:47:25 <ZWELNCH:16845366> ZWESVUSR INFO ZWEL0018I Zowe instance prepared successfully
  * (+1s) from last

### prepare components starting

- 2022-04-26 05:48:18 <ZWELNCH:16845366> ZWESVUSR INFO ZWEL0016I start component list: 'api-catalog,app-server,caching-service,discovery,files-api,gateway,jobs-api,zss'
  * (+53s) from last
  * (+16m3s) from zwe kicks in
  * (+16m34s) from beginning
- 2022-04-26 05:48:18 <ZWELNCH:16845366> ZWESVUSR INFO ZWEL0006I starting components
- 2022-04-26 05:48:18 <ZWELNCH:16845366> ZWESVUSR INFO ZWEL0012I starting console listener
- 2022-04-26 05:51:01 <ZWELS:67174492> ZWESVUSR INFO (zwe-internal-start-component:63) starting component discovery ...
  * (+2m43s) from starting components
- 2022-04-26 05:51:01 <ZWELS:67439> ZWESVUSR INFO (zwe-internal-start-component:63) starting component gateway ...
  * (+2m43s) from starting components
- 2022-04-26 05:51:02 <ZWELS:16846582> ZWESVUSR INFO (zwe-internal-start-component:63) starting component files-api ...
  * (+2m44s) from starting components
- 2022-04-26 05:51:02 <ZWELS:67174702> ZWESVUSR INFO (zwe-internal-start-component:63) starting component caching-service ...
  * (+2m44s) from starting components
- 2022-04-26 05:51:02 <ZWELS:33621717> ZWESVUSR INFO (zwe-internal-start-component:63) starting component api-catalog ...
  * (+2m44s) from starting components
- 2022-04-26 05:51:02 <ZWELS:67140> ZWESVUSR INFO (zwe-internal-start-component:63) starting component jobs-api ...
  * (+2m44s) from starting components
- 2022-04-26 05:51:03 <ZWELS:83951856> ZWESVUSR INFO (zwe-internal-start-component:63) starting component app-server ...
  * (+2m45s) from starting components
- 2022-04-26 05:51:04 <ZWELS:65751> ZWESVUSR INFO (zwe-internal-start-component:63) starting component zss ...
  * (+2m46s) from starting components

### real components starting

- 2022-04-26 05:52:26.277 [35m<ZWEEAD1:main:50399108>[0;39m ZWESVUSR [32mINFO [0;39m [36m(o.z.DataSetsAndUnixFilesApplication,DataSetsAndUnixFilesApplication.java:38)[0;39m ZWEE0000I DataSetsAndUnixFilesApplication started in 30.267 seconds
  * (+1m24s) from starting component files-api
- 2022-04-26 05:53:05.564 <ZWEAAC1:main:33623508> ZWESVUSR INFO  (o.z.a.p.s.ServiceStartupEventHandler) ZWEAM000I API Catalog Service started in 70.205 seconds
  * (+2m3s) from starting component api-catalog
- 2022-04-26 05:53:02.586 <ZWEADS1:main:83953375> ZWESVUSR INFO  (o.z.a.p.s.ServiceStartupEventHandler) ZWEAM000I Discovery Service started in 68.116 seconds
  * (+2m1s) from starting component discovery
- 2022-04-26 05:53:27.888 [35m<ZWEEAJ1:main:83953740>[0;39m ZWESVUSR [32mINFO [0;39m [36m(o.z.j.JesJobsApplication,JesJobsApplication.java:38)[0;39m ZWEE0000I JesJobsApplication started in 20.574 seconds
  * (+2m25s) from starting component jobs-api
- 2022-04-26 05:53:45.769 [35m<ZWEACS1:main:67177969>[0;39m ZWESVUSR [32mINFO [0;39m [36m(o.z.a.p.s.ServiceStartupEventHandler)[0;39m ZWEAM000I Caching Service started in 38.072 seconds
  * (+2m43s) from starting component caching-service
- 2022-04-26 05:54:11.281 <ZWEAGW1:main:67176865> ZWESVUSR INFO  (o.z.a.p.s.ServiceStartupEventHandler) ZWEAM000I Gateway Service started in 38.435 seconds
  * (+3m11s) from starting component gateway
- ZWES1014I ZIS status - 'Ok' (name='ZWESIS_STD      ', cmsRC='0', description='Ok', clientVersion='2')
  * no timestamp
- 2022-04-26 05:54:38.816 <ZWED:16844705> ZWESVUSR INFO (_zsf.apiml,EurekaClient.js:267) registered with eureka:  zlux/***:zlux:7556
  * (+3m35s) from starting component app-server
- 2022-04-26 05:54:38.845 <ZWED:16844705> ZWESVUSR INFO (_zsf.network,webserver.js:400) ZWED0130I - (HTTPS) About to start listening on 0.0.0.0:7556
  * (+3m35s) from starting component app-server
- 2022-04-26 05:54:39.443 <ZWED:16844705> ZWESVUSR INFO (_zsf.install,index.js:439) ZWED0031I - Server is ready at https://0.0.0.0:7556, Plugins successfully loaded: 100% (19/19)
  * (+3m36s) from starting component app-server
  * (+22m24s) from zwe kicks in
  * (+22m55s) from beginning

**Comment by MarkAckert** [comment]
Plan is to test again once zowe yaml schema and new config manager are complete; they may improve performance drastically.

**Comment by 1000TurquoisePogs** [comment]
As of 2.3, Zowe server installs contain a mode of `zwe` operation, enabled by either `zowe.useConfigmgr=true` in zowe.yaml, or in `--configmgr` flag in any `zwe` commands that have it.
In 2.4, this becomes the default.

This mode enables several features and validation improvements covered here https://docs.zowe.org/stable/user-guide/configmgr-using but for this ticket, I'll summarize that it leads to major performance improvements and how that is accomplished so that we can set expectations for current and future performance improvements.

# performance summary

"configmgr" mode of `zwe` is currently only supported for the `zwe start`, `zwe stop` and `zwe components` commands.  Yet, you can see 2 real-world improvements today when using it:
* `zwe start` is what was profiled above. We have seen **up to 5 to 10 times faster execution of zwe start**, such as by going from 10 minutes startup time down to 2 or 1. This seems to put it in the realm of zowe v1 performance yet zowe v2 is doing a lot more and is a lot smarter.
* **overall execution of our CICD pipeline is about 2 times faster** by comparing [new](https://github.com/zowe/zowe-install-packaging/actions/runs/3180344527/jobs/5183811455) to [old](https://github.com/zowe/zowe-install-packaging/actions/runs/3094423074/jobs/5007784584). This time includes post-startup testing in the browser etc, so real-world time to use Zowe should be even better than 2x.

# technology analysis

The speedup is accomplished by a variety of enhancements, such as
* rewriting zwe in javascript instead of shell
    * reducing i/o by reusing objects in memory made possible by the language shift
* reducing the number of processes spawned during execution
    * moving JS operations from forks to start up nodejs into the embedded JS
    * writing JS functions that have the same output as standalone programs

## Rewriting zwe in javascript
Technically rewritten in typescript and then transpiled to javascript, giving us the added benefit of static code error checking and type strictness, the shell scripts of zwe were translated into equivalent JS code. This is not nodejs, but rather an embedded JS interpreter which gives us the benefit of no prereqs, less attack surface, and ease of maintenance. 

I assume js interpreters are faster than shell for equivalent operations like iterating over an array, but I don't have numbers on this.

### Reducing i/o
Shell code has some limitations on what you can do with a variable without calling plenty of extra processes. As a result, zwe shell code that needed to act upon multiple properties within a YAML or JSON data structure would often spawn nodejs to read the file, then extract a single property, exit nodejs, do something in shell code, then spawn a new nodejs process to deal with the second property, etc.

JS code is really good at handling YAML and JSON. So, rather than doing a literal translation between the languages, sections of code dealing with YAML and JSON were simplified by loading the file once, and then acting upon the contents multiple times within the same process. I believe this area of improvement yielded the biggest speedup, whether it was due to i/o, or process spawning, or node init time, or the layers of shell functions that the code needed to pass through, all of this has been simplified so the benefits are compounded.

## Reducing process spawning
Similar to above, the JS code doesn't just reduce the amount of nodejs used, it also reduces the amount of `sed`, `grep`, `awk`, `cat` and on and on. Our use of these programs was often straightforward enough to just write a JS function that did the same thing, eliminating the cost of opening another process and sending info back-and-forth through STDOUT.
We are not done here, this area of the code can be improved even further! Do a text search in the .ts files for `shell.exec` to see how many areas remain.


# possible future improvements
* If we further reduced process spawns, we'd be that much more efficient. Aside from performance, we can completely eliminate nodejs as a prereq of zowe installs that don't use nodejs components if we take this work further.

* `zwe install` and `zwe init` are not yet covered by this code. So, while startup is much faster, the install time is unchanged. `install` and `init` do operations that rely upon system commands that probably can't be changed, like that we will always have to do MVS copies and use keytool for certificate setup. So, I don't know if the performance improvement will be as stark when these commands get "configmgr" editions. Yet, we still must do this because "configmgr" gives much better config control & config validation regardless, so we'll get quality of life improvements aside from just performance.

**Comment by MarkAckert** [comment]
Config Manager addresses the v2 performance issues. For non-config manager scenarios, performance improvement would require converting shell commands to another format - rexx, node, golang, etc. Closing this issue - converting more functionality to config manager looks like the path forward for performance improvements.
