### ISSUE TITLE
Status of extension installation configuration on zowe.yml

### ISSUE THREAD

**Issue by pablocarle** [zowe/zowe-install-packaging#2979]
Review of requested changes to support extension-specific environment variables visible for main components (API ML gateway / discovery / etc)

**Comment by 1000TurquoisePogs** [comment]
I think you will be able to use the zowe.environments section to have your own component set environment vars that are visible to other components.
The problem today is that you'd have to have someone or something modify the zowe.yaml to do that.
However, configmgr has this feature to merge together multiple yaml files, so you could have your own yaml file that just talks about zowe.environments, and then it would merge together with zowe.yaml so that every server would see the environment vars without editing zowe.yaml

Soon, zwe when using `zowe.useConfigmgr=true` should be able to find each component's own yaml files and merge it all together. This way you can ship whatever defaults you want without editing zowe.yaml
Here's an example of one we have in zss right now: https://github.com/zowe/zss/blob/v2.x/staging/defaults.yaml

We need a way for components to declare if they have a yaml and where it is located.
We will need a new manifest property to declare it. https://github.com/zowe/zss/blob/v2.x/staging/manifest.template.yaml#L17

**Comment by 1000TurquoisePogs** [comment]
I'll update this ticket with a build including that funcitonality when it exists, but it hasn't been written yet so i'm not sure if it will make it for v2.3 (end of august), or for v2.4

**Comment by 1000TurquoisePogs** [comment]
@pablocarle Also keep in mind that in the existing manifest.yaml, regardless of `zowe.useConfigmgr`, you can specify defaults for your extensions own `components.extensionname` section.
It looks like this: https://github.com/zowe/api-layer/blob/v2.x.x/gateway-package/src/main/resources/manifest.yaml#L26-L67
Those will still show up as environment variables at runtime, without modifying zowe.yaml!
So if that fits your needs, you can do this right now, even on v2.0

**Comment by MarkAckert** [comment]
Closing this as a solution appears possible, and zwe config manager is now live which also adds more possible solutions for the original question. Please re-open this if you disagree.
