### ISSUE TITLE
zwe init certificate command to detect z/OSMF root CA

### ISSUE THREAD

**Issue by skurnevich** [zowe/zowe-install-packaging#3362]
`zwe init certificate` command fails when tries to detect z/OSMF root CA to add it to the keyring. 
(Certificate setup scenario 4; RACF)

Issue seems to be related to this part of code 
https://github.com/zowe/zowe-install-packaging/blob/v2.x/staging/bin/libs/certificate.sh#L1371

It issues RACDCERT LIST ID(IZUSVR) and then tries to process the output to get the keyring name, but as a result gets an odd line containing names of all keyrings owned by IZUSVR mixed up with field names like "Label", "Certificate", "Status" etc

Then it tries to issue RACDCERT LISTRING for the given line and fails as there is no such keyring:

```
>> Generate Zowe certificate in keyring

- Detect z/OSMF keyring by listing ID(IZUSVR)
  * z/OSMF keyring name is <KEYRING_NAME_1>Ring<KEYRING_NAME_2>Label:CertificateStatus:StartEndSerial05Issuer'sLabel:CertificateStatus:StartEndSerial06Issuer's<KEYRING_NAME_4>
- Detect z/OSMF root certificate authority by listing keyring (<KEYRING_NAME_1>Ring<KEYRING_NAME_2>Label:CertificateStatus:StartEndSerial05Issuer's<KEYRING_NAME_3>Label:CertificateStatus:StartEndSerial06Issuer's<KEYRING_NAME_4>)
  * Exit code: 4
  * Output:
    RACDCERT LISTRING(<KEYRING_NAME_1>Ring<KEYRING_NAME_2>Label:CertificateStatus:StartEndSerial05Issuer's<KEYRING_NAME_3>Label:CertificateStatus:StartEndSerial06Issuer's<KEYRING_NAME_4>) ID(IZUSVR)
    IRRD114I Ring <KEYRING_NAME_1>Ring<KEYRING_NAME_2>Label:CertificateStatus:StartEndSerial05Issuer's<KEYRING_NAME_3>Label:CertificateStatu
    s:StartEndSerial06Issuer's<KEYRING_NAME_4> does not exist.
Error ZWEL0137E: z/OSMF root certificate authority is not provided (or cannot be detected) with trusting z/OSMF option enabled.
```

**Comment by Martin-Zeithaml** [comment]
I believe, there are 3 problems.
### RACF parsing
Is seems to be supposed, that only one ring is associated with that ID. On our development system, there are several rings and that's why the [parsing](https://github.com/zowe/zowe-install-packaging/blob/78f3f656d3f5db0a4cf3b3fe2a99283d7cfc816e/bin/libs/certificate.sh#L1417) is confused and produced garbage like `<KEYRING_NAME_1>Ring<KEYRING_NAME_2>Label:CertificateStatus:StartEndSerial05Issuer'sLabel:CertificateStatus:StartEndSerial06Issuer's<KEYRING_NAME_4>`

### Missing ACF2

Obviously the implementation is [RACF only](https://github.com/zowe/zowe-install-packaging/blob/78f3f656d3f5db0a4cf3b3fe2a99283d7cfc816e/bin/libs/certificate.sh#L1400).

The ACF2 does not work from `tsocmd`. However there is a feature [ACFUNIX](https://techdocs.broadcom.com/us/en/ca-mainframe-software/security/ca-acf2-for-z-os/16-0/reporting/utilities/acfunix-utility.html) for that. This feature must be setup on customer's environment.

From shell script, `JCL` is probably the most reliable way.

#### Parsing notes
* `RINGNAME`
  * Up to 237 characters in length
  * Mixed-cased characters
  * Special characters `(!&*¬-%_?:=.)`
     * Do not ask why, but you can define RINGNAME with `()`
  * Blanks are not allowed
* `LABEL`
  * 1-32 characters
  * Blanks and mixed-case characters
  * Every apostrophe must be doubled

### Missing TSS

Also missing implementation.

Here is an example of `tsocmd "TSS LIST(IZUSVR) KEYRING(ALL)"`, some values had been changed, but for the parsing idea it does not matter.

```
$ tsocmd "TSS LIST(IZUSVR) KEYRING(ALL)"
TSS LIST(IZUSVR) KEYRING(ALL)
KEYRING =  IZUSVRK          ACCESSORID = IZUSVR
KEYRING LABEL = IZUKEYRING.IZUDFLT
KEYRING HAS THE FOLLOWING CERTIFICATES CONNECTED:
  ACID(CERTAUTH)  DIGICERT(WEB12345)  DEFAULT(NO )  USAGE(CERTAUTH)
  LABLCERT(ZOSMFCA                         )
  ACID(IZUSVR  )  DIGICERT(DF123456)  DEFAULT(YES)  USAGE(PERSONAL)
  LABLCERT(DEFAULTZOSMFCERT.IZUDFLT        )
KEYRING =  IZUSVRK2         ACCESSORID = IZUSVR
KEYRING LABEL = IZUKEYRING.DIGI
KEYRING HAS THE FOLLOWING CERTIFICATES CONNECTED:
  ACID(CERTAUTH)  DIGICERT(AUTO0006)  DEFAULT(NO )  USAGE(CERTAUTH)
  LABLCERT(AUTO0006                        )
  ACID(IZUSVR  )  DIGICERT(IZUSVRS )  DEFAULT(YES)  USAGE(PERSONAL)
  LABLCERT(izusvrsig                       )
TSS0300I  LIST     FUNCTION SUCCESSFUL
```
#### Parsing notes
* There are multiple keyrings (2 at our example)
* `KEYRING LABEL` 
  * Up to 237-byte ring label, I will try to provide example with a long label to see, how the line is/or not wrapped
  * TSS documentation is silent about special chars, spaces and other parsing trouble makers
  * It seems **leading** spaces are significant, trailing spaces are ignored
    * `" A" != "A"`, but `"A " == "A"`
* `LABLCERT`
  * Up to 32 case-sensitive-characters can be specified for the label name. Spaces are allowed if you use single quotes.

```
$ tsocmd "TSS LIST(JOKER01) KEYRING(ALL)"
TSS LIST(JOKER01) KEYRING(ALL)
KEYRING =  TESTRING         ACCESSORID = JOKER01
KEYRING LABEL:
             AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA -
             AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA -
             AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA -
             AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA -
             AAAAA
KEYRING =  TEST2            ACCESSORID = JOKER01
KEYRING LABEL = -
KEYRING =  TEST3            ACCESSORID = JOKER01
KEYRING LABEL = ()
KEYRING =  TEST4            ACCESSORID = JOKER01
KEYRING LABEL = !@#$%^&*()
KEYRING =  TEST5            ACCESSORID = JOKER01
KEYRING LABEL =  A - A - A
KEYRING =  TEST6            ACCESSORID = JOKER01
KEYRING LABEL:
             AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA -
KEYRING =  TEST7            ACCESSORID = JOKER01
KEYRING LABEL:
             AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
KEYRING =  TEST8            ACCESSORID = JOKER01
KEYRING LABEL:
             AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA -
             AA
```

**Comment by bobbydixon** [comment]
I see this issue is closed, but it's not clear to me what the solution is, please can you explain?  or should I create another case for a Zowe TSS client reporting the following error running the zwe init command:

Error ZWEL0137E: z/OSMF root certificate authority is not provided (or cannot be detected) with trusting z/OSMF option enabled.

Kind regards,
Bobby

**Comment by Martin-Zeithaml** [comment]
@bobbydixon Yes, please, create new issue.
If possible, include the `zwe` command output with `--trace` parameter.
The detection of z/OSMF root CA was added to Zowe 2.15.0. Are you or customer on the latest release?
