### ISSUE TITLE
JCL templating via yaml and embedded JS

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zowe-install-packaging#3858]
**Describe the solution you'd like**
Use the `configmgr` features to define JCL templates in `yaml` file using the embedded JS.
Define template to be ready in two forms:
* With placeholder
* With actual value

**Describe alternatives you've considered**
None.

**Additional context**

`zwe install` will process the templates to be ready with placeholders:
```
//STEPLIB  DD  DSNAME={zowe.setup.dataset.authLoadlib},
```
`zwe init` will process the templates with real values:
```
//STEPLIB  DD  DSNAME=ZOWE.TEST1,
```

**Comment by 1000TurquoisePogs** [comment]
its important for there to be jcl samples in the samplib so that
1) there are samples which we can use as a form of documentation, such as in the quick start guide
2) users can prepare zowe entirely through 3270
3) users can choose to totally ignore our automation and edit them directly

user feedback has also been that they do not like conditional behavior in automation, they want to know what it is doing.

so, the power of using `configmgr` binary and putting logic into yaml is nice but given the limitations i don't see how much extra features we can leverage beyond the limitations of ZWEGENER while keeping that sample-based design
