### ISSUE TITLE
Create  new Jenkins job to test the SMP/E install

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#516]
We need a job similar to zowe-install-test, but it does the install via an SMP/E script rather than the pax script. We should probably just reuse the same smoke tests, but need to create a script for the SMP/E install.

**Comment by stevenhorsman** [comment]
Joe mentioned that CICS already have sometime that headlessly drives SMP/E install, so it's worth chatting to Will Yates or someone first.

**Comment by John-A-Davies** [comment]
I now have a POC Bourne shell script that consumes Onno's README and pax.Z files.  It runs his GIMUNZIP and then tailors and runs all the RECEIVE and APPLY jobs in sequence.  Caveats:  It has some hard-coded paths and datasets for my test environment, and it has almost no error checking, but it works.

It comes with a couple of `sed` files to perform the tailoring, and a script to delete all the files and directories that it creates, so you can re-run it.  

I will make this work-in-progress version available in Git tomorrow.  The intent is to offer an improved version of this to the Jenkins pipeline, so that it can verify that the SMP/E install works.

**Comment by John-A-Davies** [comment]
A version of the script is now in the `staging` branch of `zowe-install-test/scripts/`.  The files are
```
delete-relfiles.sh 	
gimunzip.sed 	
install-SMPE-PAX.sh 	
smpejob.sed
```

Important note:  This is only a proof of concept.  I've put it in GitHub for information only.  I am rewriting it and I will upload a new version in due course.    It won't work on your system.

**Comment by stevenhorsman** [comment]
Current plan is to produce the 1.4 smpe alpha after the 1.4 convenience release, so this will be planned early after 1.4 GA

**Comment by stevenhorsman** [comment]
Work under https://github.com/zowe/zowe-install-test/pull/109?

**Comment by John-A-Davies** [comment]
Completed by zowe-install-test PR 109 (merged)
