### ISSUE TITLE
Replace use of USS keystore with SAF keyring

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#789]
*Customer content*
Multiple customers on calls do not wish to use USS keystores to hold trusted keys of servers or the northbound key for the APIML. They wish instead to use a keyring, either an existing one or a new Zowe one

**Describe the solution you'd like**
Keystore changes - Rather than creating a new keystore in the install we can use an existing one the customer has/ provide doc to create a new one if they need, use keyrings, made keystore shared globally between zowe installs

**Comment by 1000TurquoisePogs** [comment]
It seems that nodejs can accept a buffer of bytes rather than a path to a file when it comes to keys & certs, so it would be possible to make an N-API https://nodejs.org/api/n-api.html component of zlux to grab content from a keyring, I think. I've never done either, so it will take some time to investigate, but I think this is preferable to alternatives.
