### ISSUE TITLE
zowe-check-prereq.sh with TSS

### ISSUE THREAD

**Issue by yann-59** [zowe/zowe-install-packaging#895]
Hello,

We used the zowe-check-prereq.sh script with TSS (instead of RACF) .
It try to  list the user with the command "LU IZUSVR" but it doesn't work :

Check user has the basic auth to list the resources 
Error: Unexpected response to RACF LISTUSER command 
RACF PRODUCT DISABLED: COMMAND ENDED.               

[....]
Then the script follow the next securiy's command but none works!
installer's 	group(s):                                          
Error: User is not a member of the IZUADMIN group              
                                                               
Check user can issue START/STOP commands                       
Error: User is not authorized to use OPERCMDS MVS.START.STC    
Error: User is not authorized to use OPERCMDS MVS.STOP.STC     
                                                               
Check user can issue SDSF commands                             
Info: User is not authorized to use SDSF ISF.CONNECT           
Info: User is not authorized to use SDSF ISFATTR               
Info: User is not authorized to use SDSF ISFCMD.ODSP           
Info: User is not authorized to use SDSF ISFOPER               

The script should by-pass the security check  for non-RACF site or enhanced with TSS check ?

**Comment by gatogatogato** [comment]
Same is tru for ACF2 users.

**Comment by Joe-Winchester** [comment]
@yann-59 - the zowe-check-prereqs script was created early 2019 when Zowe was first released and we haven't kept it up to date. We are planning to remove it and provide the same function in a different way and I have created Epic #923 to track the design and implementation of this, so what I'll do is assign of all your check-preqs issues as children of this so we can work on them together.

As a design question, if we provide an automated way to check the system pre-reqs, are you OK if rather than a shell script we switch to being a JCL member ?  This would remove the SDSF pre-req that we have in our unix opercmd script, and also make it easier for folks to customize, comment out sections, ...

**Comment by yann-59** [comment]
@Joe-Winchester we discuss with our zowe's team and we thought that JCL member is a better way to check the pre-req ... In our case, some pre-req can't be run by the same guy beaucse some are security 's administrator, some are system's programer and don't have the sufficient right. We'll follow the new Epic ... Thks

**Comment by stevenhorsman** [comment]
@yann-59 - Since 1.8 the yaml file and IZU user and groups are not used with the zowe server, and we've streamlined the zowe-check-prereqs.sh to remove some of the code that caused issue, so from 1.9 dev build onwards this issue won't happen.

**Comment by yann-59** [comment]
We just saw the latest release of zowe ... we are just downloading it .
Cheers.
