### ISSUE TITLE
create script to allow promote to stage update SMPE PTF data for next build

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#900]
*Customer content*

**Is your feature request related to a problem? Please describe.**

After an RC build is vetted, it is promoted to be the official build. The promote process will be updated to invoke a script that updates the data in smpe/bld/service and then commits this to Github as starting point for the next build:
-  smpe/bld/service/ptf-bucket.txt : comment out the line holding the PTF that is being promoted
-  smpe/bld/service/current-apar.txt :  remove if present (list of additional APARs)
-  smpe/bld/service/current-hold-*.txt :  remove if present (additional hold info)
-  smpe/bld/service/promoted-apar.txt : add promoted APARs to list
-  smpe/bld/service/promoted-close.txt : add formatted closing info of this PTF
-  smpe/bld/service/promoted-hold.txt : add formatted ++HOLD info of this PTF
-  smpe/bld/service/promoted-apar.txt : add promoted PTFs to list

**Describe the solution you'd like**

see above

**Describe alternatives you've considered**

none

**Additional context**

none
---
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** [type of user],  
**I want** [some goal]  
**so that** [some reason].

*Details/notes*  
[Detail - implementation notes]

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

**Comment by OnnoVdT** [comment]
[Zowe PTF data management.docx](https://github.com/zowe/zowe-install-packaging/files/3928569/Zowe.PTF.data.management.docx)

**Comment by OnnoVdT** [comment]
@jackjia-ibm Jack,
I created a new file, smpe-promote.tar, to be placed in Artifactory after an SMP/E build. This file will be the main input for the smpe-promote.sh script. .pax/post-packaging.sh and JenkinsFile are updated.

My next question is about how the promote process will call the update script, smpe-promote.sh.
I'm assuming that the invocation can pass in an argument specifying where the tar file is.
I'm also assuming that the script will be running on some Unix box (but not z/OS) and that the zowe-install-packaging repo is loaded, and my script is called from in here. This way I can figure out the location of the files that need updating (smpe/bld/service/*) based on the location of the script (smpe/bld).

**Comment by jackjia-ibm** [comment]
@OnnoVdT I updated https://github.com/zowe/zowe-install-packaging/pull/944 to upload smpe-promote.tar and ran a test build.

Few questions:
- What is the purpose of zowe-promote.tar?
- Where I can find the smpe-promote.sh? What's the purpose of this script?
- The test build created zowe-promote.tar but with zero size, so I could see the content.

FYI, we have a release pipeline defined here https://github.com/zowe/zowe-install-packaging/blob/master/Jenkinsfile.release. But the release process is just copying artifact from https://zowe.jfrog.io/zowe/webapp/#/artifacts/browse/tree/General/libs-snapshot-local/org/zowe to https://zowe.jfrog.io/zowe/webapp/#/artifacts/browse/tree/General/libs-release-local/org/zowe. It doesn't do any rebuild or modification on the artifacts will be promoted.

**Comment by OnnoVdT** [comment]
I'm writing the smpe-promote.sh script later this week. As described in the content block of this issue, this script must be run during promote so it can add information from this PTF to the files describing the previous PTFs. 
SMPE requires that each PTF knows about the previous ones to avoid regression. 
When a PTF is built (currently we're building USERMODs as PTFs have numbers that must be known by IBM's RETAIN/Shopz), the tar file will hold the info we need (see to top of this thread for the file names and their function) to update the promoted PTF info.
After the script runs, the changes must be checked into GitHub as starting point for the next PTF build.
When we talked earlier about how to transfer this info, you were not in favor of updating the pax file in Artifactory holding the logs directory, and we agreed upon this mechanism, where the promote step would update files in GitHub.

**Comment by OnnoVdT** [comment]
@jackjia-ibm pull request https://github.com/zowe/zowe-install-packaging/pull/946 holds the smpe-promote.sh script.

**Comment by jackjia-ibm** [comment]
>> Onno Van den Troost:palm_tree: 4:47 PM
https://github.com/zowe/zowe-install-packaging/pull/944 completes the PTF build work. The Zowe build pipeline can now build PTF, APAR and USERMOD. The key for selecting what kind of service is created is smpe/bld/service/ptf-bucket.txt.
Details and instructions can be found in smpe/bld/_README.txt and smpe/bld/service/_README.txt.
The build process will do as told, so it is always possible that an update to ptf-bucket.txt to build an APAR instead of PTF slips into the CR build. Therefore, @Jack (T.) Jia once we get to CR builds that must produce a PTF (March release?), you should start the build with a new option checked, BUILD_SMPE_PTF. When checked, the SMP/E build will fail if it is not creating a PTF, which gives us a chance to fix things (and chew out the person who let this slip upstream :slightly_smiling_face: ).
Next up is a script (executed during promote) to update data on promoted PTF data (new PTFs must know about the old ones). (edited) 

Thanks a lot Onno for the PR and readme. Few questions to help me understand better of the process:

- What is CR build?
- If we use `smpe/bld/service/ptf-bucket.txt` to control what kind of build (PTF/APAR/USERMOD), I think we may not need `BUILD_SMPE_PTF` parameter? Any update on the file `smpe/bld/service/ptf-bucket.txt` on critical branches supposed to be reviewed already.
- I’m reading the `_README.txt`, for USERMOD which will never be published to zowe.org, but do we need to keep a record of the USERMOD info? I assume to build this USERMOD, we have a special change on the ptf-bucket (by removing the file, or remove the non-comments lines), do we need to tag and keep the branch? Since all code eventually will be merged into staging->rc->master, based on this, I assume the USERMOD change should never be merged into staging if the staging has been updated for next PTF release. Is that correct?
- Similar question to APAR, it’s similar to PR, so I assume before we merge this APAR-fix to staging, we should have: tested the PR, reverted ptf-bucket.txt back to proper PTF number, removed apar-bucket.txt and updated current-apar.txt. Is that correct?
- After first FMID released, I assume ptf-bucket.txt on staging should be updated to the next PTF number and always be the next PTF number. And this info will be copied to rc and master branch. Is that correct?
- Based on your descriptions on promoted-*.txt, and after read your smpe-promote.sh, my understanding is after PTF is released (or even RC is created), we should create a PR on `staging` or `v?.x/staging` branch with the changes suggested in `smpe-promote.sh`. I will try to update https://github.com/zowe/zowe-install-packaging/pull/946 for this change.

**Comment by OnnoVdT** [comment]
- CR build is a typo, that should have been RC (release candidate)
- If we are certain everyone doing a review understands to importance of having ptf-bucket.txt just right, then we indeed do not need `BUILD_SMPE_PTF` parameter. But if something slips through then we won't know until a customer complains about what is being published on zowe.org. Hence the idea of a fail-safe with `BUILD_SMPE_PTF`. 

- In normal circumstances, we should only build a USERMOD when we (are getting ready to) publish an FMID. And the USERMOD would only be used by John's automated test suite for the SMPE build. Once the FMID goes live, ptf-bucket.txt will be populated by Nayer and added to master, so all future builds will start creating PTFs. Nayer is responsible for ensuring ptf-bucket.txt never runs out of PTF numbers. That said, if we have a customer who is not at the latest PTF level and requires an SMP/E-installable fix, then we have to create a USERMOD based on an older service level (this is not yet implemented, see https://github.com/zowe/zowe-install-packaging/issues/951). 
You are correct in assuming that once the staging/master branch is set for PTF builds (instead of FMID builds), no USERMOD builds should trickle up to them. So any changes to force a USERMOD build must be undone before a PR can be approved.
I'm not sure what you mean with 'keeping a record of the USERMOD info'. If the USERMOD is available in Artifactory for the rare case we need to ship one to a customer, without keeping record, then no, we don't need to keep record. If Artifactory depends on keeping record, then yes, we do need to.

- Your understanding is correct for the APAR build flow.

- After the FMID is released, Nayer will have to create a branch to introduce ptf-bucket.txt, which must be merged into staging, and from there eventually to RC and master. Once a PTF is released, ptf-buket.txt will be updated by the promote process. I'm not sure which branch you want to do this update on. I used master in my description, but thinking more about it, that is likely not the one you want to use, I'm guessing now the promote process will update staging, as the update is in fact getting things ready for the next PTF, which is the purpose of the staging branch.

- Your understanding that a PR on staging is required as part of the promote process to update promoted-* & family is correct. 
I was hoping that the promote process could automatically pull smpe-promote.tar from Artifactory, run smpe-promote.sh, create a PR & approve the changes. Your question make it sound like this will be a manual step. 
I created smpe-promote.sh to make it easy to execute the required updates (and to easily change the steps if required), so if you think that it will be better with some updates, by all means, be my guest.

**Comment by jackjia-ibm** [comment]
Thanks @OnnoVdT for the info.

For `BUILD_SMPE_PTF` parameter to prevent publishing wrong build to zowe.org, I think we don't need to worry about. We usually do at least 1 RC, normally have 2 RCs before publishing. If the team cannot figure it's wrong in 2 RCs, I think we are doomed. :)

For keeping USERMOD build, or any other APAR/PTF branch build, it's about we will clean up Artifactory periodically to free up space. Most of branch and PR builds will be removed after certain days (like 1-2 months) except for staging/rc/master branches. The cleaning is mainly for saving storage purpose to reduce cost. If those builds have a value to be kept, I will need to know and we need to find a way.

For promote, the only thing kind of blocking me is we need to figure out which `staging` to update after LTS. After we announce v2, v1 will become archived as `v1.x/staging`, and `staging` will be for building v2. So when we announce a new version, I also need to know which staging to update by knowing we are promoting a v1 or a v2 PTF. I may need to add a promote parameter to do this. This will be reflected in https://github.com/zowe/zowe-install-packaging/pull/946.

**Comment by OnnoVdT** [comment]
I'll remove BUILD_SMPE_PTF then, but will wait until Stephen is done with PR https://github.com/zowe/zowe-install-packaging/pull/944 to avoid merge conflicts. 

For cleaning up Artifactory, no need to change things. Everything except staging/rc/master is temporary, even if an APAR or USERMOD build was sent to a customer. It's not permanent/official until it made it into staging.

Good point about promote in a multi-version environment. It seems like you have a handle on it, but let me know if you need my help with this pickle.

**Comment by OnnoVdT** [comment]
BUILD_SMPE_PTF removed, new build (6) for PR https://github.com/zowe/zowe-install-packaging/pull/946 is running.
