### ISSUE TITLE
Cross memory server error as it can't find ZWESIP00 

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#916]
**Describe the bug**
ZWEXMSTC job log shows `STC05289  IEE252I MEMBER ZWESIP00 FOUND IN ZOWEAD3.PARMLIB`

**Proposed fix**
Revert `ZWEXMP00` to `ZWESIP00`

**Comment by John-A-Davies** [comment]
@jackjia-ibm FYI.

I think this is what you said about this issue : 

> Jack T. Jia Yesterday at 3:26 PM
Hi team, I think there is an error of install zss parmlib. Original parmlib in zss.pax is called ZWESIP00, and during installation, it’s renamed to ZWEXMP00. But when we check the ZWEXMSTC job log, it shows STC05289  IEE252I MEMBER ZWESIP00 FOUND IN ZOWEAD3.PARMLIB, which it’s still using `ZWESIP00` . The nightly build test doesn’t fail because we have both ZWEXMP00 and ZWESIP00. If we do a real clean installation, only ZWEXMP00 exists in the parmlib and zss will fail to start. So want to clarify what should be the correct parmlib for zss. And I need to update uninstall to clean up properly.
