### ISSUE TITLE
ZWESECUR.jcl  INVALID KEYWORD, &ZSSUSER.

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#971]
**Describe the bug**
When you run ZWESECUR.jcl, you get this error, even though it returns RC=00
```
 /* userid for ZSS, cross memory server                               */
 READY
   LISTUSER &ZSSUSER. OMVS
 IKJ56712I INVALID KEYWORD, &ZSSUSER.
```

**To Reproduce**
```
//         SET XMEMUSER=ZWESIUSR     * userid for xmem started task
//         SET  AUXUSER=&XMEMUSER.   * userid for xmem AUX started task
```

**Expected behavior**
```
//         SET ZSSUSER=ZWESIUSR     * userid for xmem started task             
//         SET  AUXUSER=&ZSSUSER.   * userid for xmem AUX started task         
```

**Additional context**
This is because ZWESECUR specifies XMEMUSER instead of ZSSUSER.

**Comment by John-A-Davies** [comment]
Similarly,
```
/* started task for ZSS, cross memory server                         */
 READY
   RLIST   STARTED &ZSSSTC..* ALL STDATA
 ICH13003I &ZSSSTC..* NOT FOUND
```
so 
`//         SET  XMEMSTC=ZWESISTC     * xmem started task name`
should be
`//         SET  ZSSSTC=ZWESISTC     * xmem started task name`

**Comment by OnnoVdT** [comment]
Problem was introduced with https://github.com/zowe/zowe-install-packaging/commit/6a75f7b5e74cbf2129877305c505e1283b1d689a#diff-9b1b3c63f076e8720fa7499a13ea6bba, where the SET statement was updated without matching updates in the rest of the JCL.

**Comment by OnnoVdT** [comment]
Not sure why, but even with a new branch Git won't let me update, and I can't get git pull to work. So I'm attaching the fix here and you can try to update.
[ZWESECUR.jcl.txt](https://github.com/zowe/zowe-install-packaging/files/4061241/ZWESECUR.jcl.txt)

/c/zowe-git/zwesecur/zowe-install-packaging (zwesecur)
$ git status
On branch zwesecur
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   files/jcl/ZWESECUR.jcl


/c/zowe-git/zwesecur/zowe-install-packaging (zwesecur)
$ git commit -s -m 'propagate variable name change through rest of JCL'
[zwesecur 9016af5] propagate variable name change through rest of JCL
 1 file changed, 47 insertions(+), 47 deletions(-)

/c/zowe-git/zwesecur/zowe-install-packaging (zwesecur)
$ git push --set-upstream origin zwesecur
To github.com:zowe/zowe-install-packaging.git
 ! [rejected]        zwesecur -> zwesecur (non-fast-forward)
error: failed to push some refs to 'git@github.com:zowe/zowe-install-packaging.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by OnnoVdT** [comment]
@stevenhorsman I noticed that in ZWESECUR you updated the names for the started tasks to match the shipping names, like ZWESVSTC. My understanding was that we during config, the started tasks are copied out of SZWESAMP with a different name than the shipping name, like ZOWESVR. So this JCL should use that name (ZOWESVR) as default. This is especially important for ZWESAUX, as this name is hardcoded as default in ZSS, changing it requires the customer to set a ZSS config variable.
So I changed them back in my update (attempt, see previous post), but I'm not sure anymore what name we planned on using for the ZSS started task, so I picked ZOWEZSS to stay in the 7 char limit and to stay consistent with ZOWESVR (but it is inconsistnet with ZWESAUX). Change it as needed.

**Comment by stevenhorsman** [comment]
Hi Onno, I've lost track of what where the names changed, but they are currently created as ZWESVSTC, ZWESISTC and ZWESASTC in SZWESAMP and I was assured by @Joe-Winchester that these were correct and final - hence the ZWESECUR updated to match?

**Comment by John-A-Davies** [comment]
According to #864, the STC names are
```
ZWESVSTC
ZWESISTC
ZWESASTC
```
and those values are used in the SAF statements in ZWESECUR.jcl - no change there.

But this issue is about inconsistent use of JCL variables; some of the SET statements used different variable names from the body of the JCL deck, as per @OnnoVdT Onno's first comment.  

I already made those required JCL variable name corrections in the SET statements, in my branch `zwesecur`.   
I will create a PR to action those changes.

**Comment by OnnoVdT** [comment]
I created https://github.com/zowe/zowe-install-packaging/issues/978 for the STC naming.
And I think I now know why my push failed, I was also using a branch named zwesecur.
